//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.31 at 04:47:20 PM CEST 
//


package hu.warchef.nav.domain.charlie;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Aircraft
 * 
 * <p>Java class for AircraftType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AircraftType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="takeOffWeight" type="{http://schemas.nav.gov.hu/OSA/2.0/data}QuantityType"/&gt;
 *         &lt;element name="airCargo" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="operationHours" type="{http://schemas.nav.gov.hu/OSA/2.0/data}QuantityType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AircraftType", namespace = "http://schemas.nav.gov.hu/OSA/2.0/data", propOrder = {
    "takeOffWeight",
    "airCargo",
    "operationHours"
})
public class AircraftType {

    @XmlElement(required = true)
    protected BigDecimal takeOffWeight;
    @XmlElement(defaultValue = "false")
    protected boolean airCargo;
    @XmlElement(required = true)
    protected BigDecimal operationHours;

    /**
     * Gets the value of the takeOffWeight property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTakeOffWeight() {
        return takeOffWeight;
    }

    /**
     * Sets the value of the takeOffWeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTakeOffWeight(BigDecimal value) {
        this.takeOffWeight = value;
    }

    /**
     * Gets the value of the airCargo property.
     * 
     */
    public boolean isAirCargo() {
        return airCargo;
    }

    /**
     * Sets the value of the airCargo property.
     * 
     */
    public void setAirCargo(boolean value) {
        this.airCargo = value;
    }

    /**
     * Gets the value of the operationHours property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getOperationHours() {
        return operationHours;
    }

    /**
     * Sets the value of the operationHours property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setOperationHours(BigDecimal value) {
        this.operationHours = value;
    }

}
