//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.31 at 04:47:20 PM CEST 
//


package hu.warchef.nav.domain.charlie;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AnnulmentVerificationStatusType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AnnulmentVerificationStatusType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="NOT_VERIFIABLE"/&gt;
 *     &lt;enumeration value="VERIFICATION_PENDING"/&gt;
 *     &lt;enumeration value="VERIFICATION_DONE"/&gt;
 *     &lt;enumeration value="VERIFICATION_REJECTED"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "AnnulmentVerificationStatusType")
@XmlEnum
public enum AnnulmentVerificationStatusType {


    /**
     * The technical annulment is not verifiable due to client error
     * 
     */
    NOT_VERIFIABLE,

    /**
     * The technical annulment is awaiting verification
     * 
     */
    VERIFICATION_PENDING,

    /**
     * The technical annulment has been verified
     * 
     */
    VERIFICATION_DONE,

    /**
     * The technical annulment has been rejected
     * 
     */
    VERIFICATION_REJECTED;

    public String value() {
        return name();
    }

    public static AnnulmentVerificationStatusType fromValue(String v) {
        return valueOf(v);
    }

}
