//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.31 at 04:47:20 PM CEST 
//


package hu.warchef.nav.domain.charlie;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InvoiceAppearanceType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="InvoiceAppearanceType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="PAPER"/&gt;
 *     &lt;enumeration value="ELECTRONIC"/&gt;
 *     &lt;enumeration value="EDI"/&gt;
 *     &lt;enumeration value="UNKNOWN"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "InvoiceAppearanceType", namespace = "http://schemas.nav.gov.hu/OSA/2.0/data")
@XmlEnum
public enum InvoiceAppearanceType {


    /**
     * Invoice issued on paper
     * 
     */
    PAPER,

    /**
     * Electronic invoice (non-EDI)
     * 
     */
    ELECTRONIC,

    /**
     * EDI invoice
     * 
     */
    EDI,

    /**
     * The software cannot be identify the form of appearance of the invoice or it is unknown at the time of issue
     * 
     */
    UNKNOWN;

    public String value() {
        return name();
    }

    public static InvoiceAppearanceType fromValue(String v) {
        return valueOf(v);
    }

}
