//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.31 at 04:47:20 PM CEST 
//


package hu.warchef.nav.domain.charlie;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Line gross data
 * 
 * <p>Java class for LineGrossAmountDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LineGrossAmountDataType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="lineGrossAmountNormal" type="{http://schemas.nav.gov.hu/OSA/2.0/data}MonetaryType"/&gt;
 *         &lt;element name="lineGrossAmountNormalHUF" type="{http://schemas.nav.gov.hu/OSA/2.0/data}MonetaryType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LineGrossAmountDataType", namespace = "http://schemas.nav.gov.hu/OSA/2.0/data", propOrder = {
    "lineGrossAmountNormal",
    "lineGrossAmountNormalHUF"
})
public class LineGrossAmountDataType {

    @XmlElement(required = true)
    protected BigDecimal lineGrossAmountNormal;
    @XmlElement(required = true)
    protected BigDecimal lineGrossAmountNormalHUF;

    /**
     * Gets the value of the lineGrossAmountNormal property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLineGrossAmountNormal() {
        return lineGrossAmountNormal;
    }

    /**
     * Sets the value of the lineGrossAmountNormal property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLineGrossAmountNormal(BigDecimal value) {
        this.lineGrossAmountNormal = value;
    }

    /**
     * Gets the value of the lineGrossAmountNormalHUF property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLineGrossAmountNormalHUF() {
        return lineGrossAmountNormalHUF;
    }

    /**
     * Sets the value of the lineGrossAmountNormalHUF property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLineGrossAmountNormalHUF(BigDecimal value) {
        this.lineGrossAmountNormalHUF = value;
    }

}
