//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.31 at 04:47:20 PM CEST 
//


package hu.warchef.nav.domain.charlie;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Mandatory params of the invoice query
 * 
 * <p>Java class for MandatoryQueryParamsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MandatoryQueryParamsType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="invoiceIssueDate" type="{http://schemas.nav.gov.hu/OSA/2.0/api}DateIntervalParamType"/&gt;
 *         &lt;element name="insDate" type="{http://schemas.nav.gov.hu/OSA/2.0/api}DateTimeIntervalParamType"/&gt;
 *         &lt;element name="originalInvoiceNumber" type="{http://schemas.nav.gov.hu/OSA/2.0/data}SimpleText50NotBlankType"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MandatoryQueryParamsType", propOrder = {
    "invoiceIssueDate",
    "insDate",
    "originalInvoiceNumber"
})
public class MandatoryQueryParamsType {

    protected DateIntervalParamType invoiceIssueDate;
    protected DateTimeIntervalParamType insDate;
    protected String originalInvoiceNumber;

    /**
     * Gets the value of the invoiceIssueDate property.
     * 
     * @return
     *     possible object is
     *     {@link DateIntervalParamType }
     *     
     */
    public DateIntervalParamType getInvoiceIssueDate() {
        return invoiceIssueDate;
    }

    /**
     * Sets the value of the invoiceIssueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateIntervalParamType }
     *     
     */
    public void setInvoiceIssueDate(DateIntervalParamType value) {
        this.invoiceIssueDate = value;
    }

    /**
     * Gets the value of the insDate property.
     * 
     * @return
     *     possible object is
     *     {@link DateTimeIntervalParamType }
     *     
     */
    public DateTimeIntervalParamType getInsDate() {
        return insDate;
    }

    /**
     * Sets the value of the insDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTimeIntervalParamType }
     *     
     */
    public void setInsDate(DateTimeIntervalParamType value) {
        this.insDate = value;
    }

    /**
     * Gets the value of the originalInvoiceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginalInvoiceNumber() {
        return originalInvoiceNumber;
    }

    /**
     * Sets the value of the originalInvoiceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginalInvoiceNumber(String value) {
        this.originalInvoiceNumber = value;
    }

}
