//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.31 at 04:47:20 PM CEST 
//


package hu.warchef.nav.domain.charlie;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProductStreamType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ProductStreamType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="BATTERY"/&gt;
 *     &lt;enumeration value="PACKAGING"/&gt;
 *     &lt;enumeration value="OTHER_PETROL"/&gt;
 *     &lt;enumeration value="ELECTRONIC"/&gt;
 *     &lt;enumeration value="TIRE"/&gt;
 *     &lt;enumeration value="COMMERCIAL"/&gt;
 *     &lt;enumeration value="PLASTIC"/&gt;
 *     &lt;enumeration value="OTHER_CHEMICAL"/&gt;
 *     &lt;enumeration value="PAPER"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "ProductStreamType", namespace = "http://schemas.nav.gov.hu/OSA/2.0/data")
@XmlEnum
public enum ProductStreamType {


    /**
     * Battery
     * 
     */
    BATTERY,

    /**
     * Packaging products
     * 
     */
    PACKAGING,

    /**
     * Other petroleum product
     * 
     */
    OTHER_PETROL,

    /**
     * The electric appliance, electronic equipment
     * 
     */
    ELECTRONIC,

    /**
     * Tire
     * 
     */
    TIRE,

    /**
     * Commercial printing paper
     * 
     */
    COMMERCIAL,

    /**
     * Other plastic product
     * 
     */
    PLASTIC,

    /**
     * Other chemical product
     * 
     */
    OTHER_CHEMICAL,

    /**
     * Paper stationery
     * 
     */
    PAPER;

    public String value() {
        return name();
    }

    public static ProductStreamType fromValue(String v) {
        return valueOf(v);
    }

}
