//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.31 at 04:47:20 PM CEST 
//


package hu.warchef.nav.domain.charlie;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for QueryOperatorType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="QueryOperatorType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="EQ"/&gt;
 *     &lt;enumeration value="GT"/&gt;
 *     &lt;enumeration value="GTE"/&gt;
 *     &lt;enumeration value="LT"/&gt;
 *     &lt;enumeration value="LTE"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "QueryOperatorType")
@XmlEnum
public enum QueryOperatorType {


    /**
     * Equals
     * 
     */
    EQ,

    /**
     * Greater than relation
     * 
     */
    GT,

    /**
     * Greater or equals relation
     * 
     */
    GTE,

    /**
     * Less than relation
     * 
     */
    LT,

    /**
     * Less or equals relation
     * 
     */
    LTE;

    public String value() {
        return name();
    }

    public static QueryOperatorType fromValue(String v) {
        return valueOf(v);
    }

}
