//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.31 at 04:47:20 PM CEST 
//


package hu.warchef.nav.domain.charlie;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Request type of the POST /queryInvoiceData REST operation
 * 
 * <p>Java class for QueryInvoiceDataRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QueryInvoiceDataRequestType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://schemas.nav.gov.hu/OSA/2.0/api}BasicRequestType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="invoiceNumberQuery" type="{http://schemas.nav.gov.hu/OSA/2.0/api}InvoiceNumberQueryType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QueryInvoiceDataRequestType", propOrder = {
    "invoiceNumberQuery"
})
@XmlSeeAlso({
    QueryInvoiceDataRequest.class,
    QueryInvoiceCheckRequest.class
})
public class QueryInvoiceDataRequestType
    extends BasicRequestType
{

    @XmlElement(required = true)
    protected InvoiceNumberQueryType invoiceNumberQuery;

    /**
     * Gets the value of the invoiceNumberQuery property.
     * 
     * @return
     *     possible object is
     *     {@link InvoiceNumberQueryType }
     *     
     */
    public InvoiceNumberQueryType getInvoiceNumberQuery() {
        return invoiceNumberQuery;
    }

    /**
     * Sets the value of the invoiceNumberQuery property.
     * 
     * @param value
     *     allowed object is
     *     {@link InvoiceNumberQueryType }
     *     
     */
    public void setInvoiceNumberQuery(InvoiceNumberQueryType value) {
        this.invoiceNumberQuery = value;
    }

}
