//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.31 at 04:47:20 PM CEST 
//


package hu.warchef.nav.domain.charlie;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Response data of the taxpayer query
 * 
 * <p>Java class for TaxpayerDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TaxpayerDataType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="taxpayerName" type="{http://schemas.nav.gov.hu/OSA/2.0/data}SimpleText512NotBlankType"/&gt;
 *         &lt;element name="taxpayerShortName" type="{http://schemas.nav.gov.hu/OSA/2.0/data}SimpleText200NotBlankType" minOccurs="0"/&gt;
 *         &lt;element name="taxNumberDetail" type="{http://schemas.nav.gov.hu/OSA/2.0/data}TaxNumberType"/&gt;
 *         &lt;element name="vatGroupMembership" type="{http://schemas.nav.gov.hu/OSA/2.0/data}TaxpayerIdType" minOccurs="0"/&gt;
 *         &lt;element name="taxpayerAddressList" type="{http://schemas.nav.gov.hu/OSA/2.0/api}TaxpayerAddressListType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TaxpayerDataType", propOrder = {
    "taxpayerName",
    "taxpayerShortName",
    "taxNumberDetail",
    "vatGroupMembership",
    "taxpayerAddressList"
})
public class TaxpayerDataType {

    @XmlElement(required = true)
    protected String taxpayerName;
    protected String taxpayerShortName;
    @XmlElement(required = true)
    protected TaxNumberType taxNumberDetail;
    protected String vatGroupMembership;
    protected TaxpayerAddressListType taxpayerAddressList;

    /**
     * Gets the value of the taxpayerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxpayerName() {
        return taxpayerName;
    }

    /**
     * Sets the value of the taxpayerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxpayerName(String value) {
        this.taxpayerName = value;
    }

    /**
     * Gets the value of the taxpayerShortName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxpayerShortName() {
        return taxpayerShortName;
    }

    /**
     * Sets the value of the taxpayerShortName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxpayerShortName(String value) {
        this.taxpayerShortName = value;
    }

    /**
     * Gets the value of the taxNumberDetail property.
     * 
     * @return
     *     possible object is
     *     {@link TaxNumberType }
     *     
     */
    public TaxNumberType getTaxNumberDetail() {
        return taxNumberDetail;
    }

    /**
     * Sets the value of the taxNumberDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaxNumberType }
     *     
     */
    public void setTaxNumberDetail(TaxNumberType value) {
        this.taxNumberDetail = value;
    }

    /**
     * Gets the value of the vatGroupMembership property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVatGroupMembership() {
        return vatGroupMembership;
    }

    /**
     * Sets the value of the vatGroupMembership property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVatGroupMembership(String value) {
        this.vatGroupMembership = value;
    }

    /**
     * Gets the value of the taxpayerAddressList property.
     * 
     * @return
     *     possible object is
     *     {@link TaxpayerAddressListType }
     *     
     */
    public TaxpayerAddressListType getTaxpayerAddressList() {
        return taxpayerAddressList;
    }

    /**
     * Sets the value of the taxpayerAddressList property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaxpayerAddressListType }
     *     
     */
    public void setTaxpayerAddressList(TaxpayerAddressListType value) {
        this.taxpayerAddressList = value;
    }

}
