//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.31 at 04:47:20 PM CEST 
//


package hu.warchef.nav.domain.charlie;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Net data of given tax rate
 * 
 * <p>Java class for VatRateNetDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VatRateNetDataType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="vatRateNetAmount" type="{http://schemas.nav.gov.hu/OSA/2.0/data}MonetaryType"/&gt;
 *         &lt;element name="vatRateNetAmountHUF" type="{http://schemas.nav.gov.hu/OSA/2.0/data}MonetaryType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VatRateNetDataType", namespace = "http://schemas.nav.gov.hu/OSA/2.0/data", propOrder = {
    "vatRateNetAmount",
    "vatRateNetAmountHUF"
})
public class VatRateNetDataType {

    @XmlElement(required = true)
    protected BigDecimal vatRateNetAmount;
    @XmlElement(required = true)
    protected BigDecimal vatRateNetAmountHUF;

    /**
     * Gets the value of the vatRateNetAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVatRateNetAmount() {
        return vatRateNetAmount;
    }

    /**
     * Sets the value of the vatRateNetAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVatRateNetAmount(BigDecimal value) {
        this.vatRateNetAmount = value;
    }

    /**
     * Gets the value of the vatRateNetAmountHUF property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVatRateNetAmountHUF() {
        return vatRateNetAmountHUF;
    }

    /**
     * Sets the value of the vatRateNetAmountHUF property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVatRateNetAmountHUF(BigDecimal value) {
        this.vatRateNetAmountHUF = value;
    }

}
