//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.31 at 04:47:20 PM CEST 
//


package hu.warchef.nav.domain.charlie;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Data of vessel
 * 
 * <p>Java class for VesselType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VesselType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="length" type="{http://schemas.nav.gov.hu/OSA/2.0/data}QuantityType"/&gt;
 *         &lt;element name="activityReferred" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="sailedHours" type="{http://schemas.nav.gov.hu/OSA/2.0/data}QuantityType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VesselType", namespace = "http://schemas.nav.gov.hu/OSA/2.0/data", propOrder = {
    "length",
    "activityReferred",
    "sailedHours"
})
public class VesselType {

    @XmlElement(required = true)
    protected BigDecimal length;
    @XmlElement(defaultValue = "false")
    protected boolean activityReferred;
    @XmlElement(required = true)
    protected BigDecimal sailedHours;

    /**
     * Gets the value of the length property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLength() {
        return length;
    }

    /**
     * Sets the value of the length property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLength(BigDecimal value) {
        this.length = value;
    }

    /**
     * Gets the value of the activityReferred property.
     * 
     */
    public boolean isActivityReferred() {
        return activityReferred;
    }

    /**
     * Sets the value of the activityReferred property.
     * 
     */
    public void setActivityReferred(boolean value) {
        this.activityReferred = value;
    }

    /**
     * Gets the value of the sailedHours property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSailedHours() {
        return sailedHours;
    }

    /**
     * Sets the value of the sailedHours property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSailedHours(BigDecimal value) {
        this.sailedHours = value;
    }

}
