//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.31 at 04:47:15 PM CEST 
//


package hu.warchef.nav.domain.delta;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Basic request data
 * 
 * <p>Java class for BasicRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BasicRequestType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="header" type="{http://schemas.nav.gov.hu/NTCA/1.0/common}BasicHeaderType"/&gt;
 *         &lt;element name="user" type="{http://schemas.nav.gov.hu/NTCA/1.0/common}UserHeaderType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BasicRequestType", namespace = "http://schemas.nav.gov.hu/NTCA/1.0/common", propOrder = {
    "header",
    "user"
})
@XmlSeeAlso({
    BasicOnlineInvoiceRequestType.class
})
public class BasicRequestType {

    @XmlElement(required = true)
    protected BasicHeaderType header;
    @XmlElement(required = true)
    protected UserHeaderType user;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link BasicHeaderType }
     *     
     */
    public BasicHeaderType getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link BasicHeaderType }
     *     
     */
    public void setHeader(BasicHeaderType value) {
        this.header = value;
    }

    /**
     * Gets the value of the user property.
     * 
     * @return
     *     possible object is
     *     {@link UserHeaderType }
     *     
     */
    public UserHeaderType getUser() {
        return user;
    }

    /**
     * Sets the value of the user property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserHeaderType }
     *     
     */
    public void setUser(UserHeaderType value) {
        this.user = value;
    }

}
