//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.31 at 04:47:15 PM CEST 
//


package hu.warchef.nav.domain.delta;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Other conventionally named data to assist in invoice processing
 * 
 * <p>Java class for ConventionalInvoiceInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ConventionalInvoiceInfoType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="orderNumbers" type="{http://schemas.nav.gov.hu/OSA/3.0/data}OrderNumbersType" minOccurs="0"/&gt;
 *         &lt;element name="deliveryNotes" type="{http://schemas.nav.gov.hu/OSA/3.0/data}DeliveryNotesType" minOccurs="0"/&gt;
 *         &lt;element name="shippingDates" type="{http://schemas.nav.gov.hu/OSA/3.0/data}ShippingDatesType" minOccurs="0"/&gt;
 *         &lt;element name="contractNumbers" type="{http://schemas.nav.gov.hu/OSA/3.0/data}ContractNumbersType" minOccurs="0"/&gt;
 *         &lt;element name="supplierCompanyCodes" type="{http://schemas.nav.gov.hu/OSA/3.0/data}SupplierCompanyCodesType" minOccurs="0"/&gt;
 *         &lt;element name="customerCompanyCodes" type="{http://schemas.nav.gov.hu/OSA/3.0/data}CustomerCompanyCodesType" minOccurs="0"/&gt;
 *         &lt;element name="dealerCodes" type="{http://schemas.nav.gov.hu/OSA/3.0/data}DealerCodesType" minOccurs="0"/&gt;
 *         &lt;element name="costCenters" type="{http://schemas.nav.gov.hu/OSA/3.0/data}CostCentersType" minOccurs="0"/&gt;
 *         &lt;element name="projectNumbers" type="{http://schemas.nav.gov.hu/OSA/3.0/data}ProjectNumbersType" minOccurs="0"/&gt;
 *         &lt;element name="generalLedgerAccountNumbers" type="{http://schemas.nav.gov.hu/OSA/3.0/data}GeneralLedgerAccountNumbersType" minOccurs="0"/&gt;
 *         &lt;element name="glnNumbersSupplier" type="{http://schemas.nav.gov.hu/OSA/3.0/data}GlnNumbersType" minOccurs="0"/&gt;
 *         &lt;element name="glnNumbersCustomer" type="{http://schemas.nav.gov.hu/OSA/3.0/data}GlnNumbersType" minOccurs="0"/&gt;
 *         &lt;element name="materialNumbers" type="{http://schemas.nav.gov.hu/OSA/3.0/data}MaterialNumbersType" minOccurs="0"/&gt;
 *         &lt;element name="itemNumbers" type="{http://schemas.nav.gov.hu/OSA/3.0/data}ItemNumbersType" minOccurs="0"/&gt;
 *         &lt;element name="ekaerIds" type="{http://schemas.nav.gov.hu/OSA/3.0/data}EkaerIdsType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConventionalInvoiceInfoType", namespace = "http://schemas.nav.gov.hu/OSA/3.0/data", propOrder = {
    "orderNumbers",
    "deliveryNotes",
    "shippingDates",
    "contractNumbers",
    "supplierCompanyCodes",
    "customerCompanyCodes",
    "dealerCodes",
    "costCenters",
    "projectNumbers",
    "generalLedgerAccountNumbers",
    "glnNumbersSupplier",
    "glnNumbersCustomer",
    "materialNumbers",
    "itemNumbers",
    "ekaerIds"
})
public class ConventionalInvoiceInfoType {

    protected OrderNumbersType orderNumbers;
    protected DeliveryNotesType deliveryNotes;
    protected ShippingDatesType shippingDates;
    protected ContractNumbersType contractNumbers;
    protected SupplierCompanyCodesType supplierCompanyCodes;
    protected CustomerCompanyCodesType customerCompanyCodes;
    protected DealerCodesType dealerCodes;
    protected CostCentersType costCenters;
    protected ProjectNumbersType projectNumbers;
    protected GeneralLedgerAccountNumbersType generalLedgerAccountNumbers;
    protected GlnNumbersType glnNumbersSupplier;
    protected GlnNumbersType glnNumbersCustomer;
    protected MaterialNumbersType materialNumbers;
    protected ItemNumbersType itemNumbers;
    protected EkaerIdsType ekaerIds;

    /**
     * Gets the value of the orderNumbers property.
     * 
     * @return
     *     possible object is
     *     {@link OrderNumbersType }
     *     
     */
    public OrderNumbersType getOrderNumbers() {
        return orderNumbers;
    }

    /**
     * Sets the value of the orderNumbers property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderNumbersType }
     *     
     */
    public void setOrderNumbers(OrderNumbersType value) {
        this.orderNumbers = value;
    }

    /**
     * Gets the value of the deliveryNotes property.
     * 
     * @return
     *     possible object is
     *     {@link DeliveryNotesType }
     *     
     */
    public DeliveryNotesType getDeliveryNotes() {
        return deliveryNotes;
    }

    /**
     * Sets the value of the deliveryNotes property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeliveryNotesType }
     *     
     */
    public void setDeliveryNotes(DeliveryNotesType value) {
        this.deliveryNotes = value;
    }

    /**
     * Gets the value of the shippingDates property.
     * 
     * @return
     *     possible object is
     *     {@link ShippingDatesType }
     *     
     */
    public ShippingDatesType getShippingDates() {
        return shippingDates;
    }

    /**
     * Sets the value of the shippingDates property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShippingDatesType }
     *     
     */
    public void setShippingDates(ShippingDatesType value) {
        this.shippingDates = value;
    }

    /**
     * Gets the value of the contractNumbers property.
     * 
     * @return
     *     possible object is
     *     {@link ContractNumbersType }
     *     
     */
    public ContractNumbersType getContractNumbers() {
        return contractNumbers;
    }

    /**
     * Sets the value of the contractNumbers property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContractNumbersType }
     *     
     */
    public void setContractNumbers(ContractNumbersType value) {
        this.contractNumbers = value;
    }

    /**
     * Gets the value of the supplierCompanyCodes property.
     * 
     * @return
     *     possible object is
     *     {@link SupplierCompanyCodesType }
     *     
     */
    public SupplierCompanyCodesType getSupplierCompanyCodes() {
        return supplierCompanyCodes;
    }

    /**
     * Sets the value of the supplierCompanyCodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link SupplierCompanyCodesType }
     *     
     */
    public void setSupplierCompanyCodes(SupplierCompanyCodesType value) {
        this.supplierCompanyCodes = value;
    }

    /**
     * Gets the value of the customerCompanyCodes property.
     * 
     * @return
     *     possible object is
     *     {@link CustomerCompanyCodesType }
     *     
     */
    public CustomerCompanyCodesType getCustomerCompanyCodes() {
        return customerCompanyCodes;
    }

    /**
     * Sets the value of the customerCompanyCodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomerCompanyCodesType }
     *     
     */
    public void setCustomerCompanyCodes(CustomerCompanyCodesType value) {
        this.customerCompanyCodes = value;
    }

    /**
     * Gets the value of the dealerCodes property.
     * 
     * @return
     *     possible object is
     *     {@link DealerCodesType }
     *     
     */
    public DealerCodesType getDealerCodes() {
        return dealerCodes;
    }

    /**
     * Sets the value of the dealerCodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link DealerCodesType }
     *     
     */
    public void setDealerCodes(DealerCodesType value) {
        this.dealerCodes = value;
    }

    /**
     * Gets the value of the costCenters property.
     * 
     * @return
     *     possible object is
     *     {@link CostCentersType }
     *     
     */
    public CostCentersType getCostCenters() {
        return costCenters;
    }

    /**
     * Sets the value of the costCenters property.
     * 
     * @param value
     *     allowed object is
     *     {@link CostCentersType }
     *     
     */
    public void setCostCenters(CostCentersType value) {
        this.costCenters = value;
    }

    /**
     * Gets the value of the projectNumbers property.
     * 
     * @return
     *     possible object is
     *     {@link ProjectNumbersType }
     *     
     */
    public ProjectNumbersType getProjectNumbers() {
        return projectNumbers;
    }

    /**
     * Sets the value of the projectNumbers property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProjectNumbersType }
     *     
     */
    public void setProjectNumbers(ProjectNumbersType value) {
        this.projectNumbers = value;
    }

    /**
     * Gets the value of the generalLedgerAccountNumbers property.
     * 
     * @return
     *     possible object is
     *     {@link GeneralLedgerAccountNumbersType }
     *     
     */
    public GeneralLedgerAccountNumbersType getGeneralLedgerAccountNumbers() {
        return generalLedgerAccountNumbers;
    }

    /**
     * Sets the value of the generalLedgerAccountNumbers property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeneralLedgerAccountNumbersType }
     *     
     */
    public void setGeneralLedgerAccountNumbers(GeneralLedgerAccountNumbersType value) {
        this.generalLedgerAccountNumbers = value;
    }

    /**
     * Gets the value of the glnNumbersSupplier property.
     * 
     * @return
     *     possible object is
     *     {@link GlnNumbersType }
     *     
     */
    public GlnNumbersType getGlnNumbersSupplier() {
        return glnNumbersSupplier;
    }

    /**
     * Sets the value of the glnNumbersSupplier property.
     * 
     * @param value
     *     allowed object is
     *     {@link GlnNumbersType }
     *     
     */
    public void setGlnNumbersSupplier(GlnNumbersType value) {
        this.glnNumbersSupplier = value;
    }

    /**
     * Gets the value of the glnNumbersCustomer property.
     * 
     * @return
     *     possible object is
     *     {@link GlnNumbersType }
     *     
     */
    public GlnNumbersType getGlnNumbersCustomer() {
        return glnNumbersCustomer;
    }

    /**
     * Sets the value of the glnNumbersCustomer property.
     * 
     * @param value
     *     allowed object is
     *     {@link GlnNumbersType }
     *     
     */
    public void setGlnNumbersCustomer(GlnNumbersType value) {
        this.glnNumbersCustomer = value;
    }

    /**
     * Gets the value of the materialNumbers property.
     * 
     * @return
     *     possible object is
     *     {@link MaterialNumbersType }
     *     
     */
    public MaterialNumbersType getMaterialNumbers() {
        return materialNumbers;
    }

    /**
     * Sets the value of the materialNumbers property.
     * 
     * @param value
     *     allowed object is
     *     {@link MaterialNumbersType }
     *     
     */
    public void setMaterialNumbers(MaterialNumbersType value) {
        this.materialNumbers = value;
    }

    /**
     * Gets the value of the itemNumbers property.
     * 
     * @return
     *     possible object is
     *     {@link ItemNumbersType }
     *     
     */
    public ItemNumbersType getItemNumbers() {
        return itemNumbers;
    }

    /**
     * Sets the value of the itemNumbers property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemNumbersType }
     *     
     */
    public void setItemNumbers(ItemNumbersType value) {
        this.itemNumbers = value;
    }

    /**
     * Gets the value of the ekaerIds property.
     * 
     * @return
     *     possible object is
     *     {@link EkaerIdsType }
     *     
     */
    public EkaerIdsType getEkaerIds() {
        return ekaerIds;
    }

    /**
     * Sets the value of the ekaerIds property.
     * 
     * @param value
     *     allowed object is
     *     {@link EkaerIdsType }
     *     
     */
    public void setEkaerIds(EkaerIdsType value) {
        this.ekaerIds = value;
    }

}
