//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.31 at 04:47:15 PM CEST 
//


package hu.warchef.nav.domain.delta;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Tax number or group identification number, under which the purchase of goods or services is done
 * 
 * <p>Java class for CustomerTaxNumberType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CustomerTaxNumberType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://schemas.nav.gov.hu/OSA/3.0/base}TaxNumberType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="groupMemberTaxNumber" type="{http://schemas.nav.gov.hu/OSA/3.0/base}TaxNumberType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CustomerTaxNumberType", namespace = "http://schemas.nav.gov.hu/OSA/3.0/data", propOrder = {
    "groupMemberTaxNumber"
})
public class CustomerTaxNumberType
    extends TaxNumberType
{

    protected TaxNumberType groupMemberTaxNumber;

    /**
     * Gets the value of the groupMemberTaxNumber property.
     * 
     * @return
     *     possible object is
     *     {@link TaxNumberType }
     *     
     */
    public TaxNumberType getGroupMemberTaxNumber() {
        return groupMemberTaxNumber;
    }

    /**
     * Sets the value of the groupMemberTaxNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaxNumberType }
     *     
     */
    public void setGroupMemberTaxNumber(TaxNumberType value) {
        this.groupMemberTaxNumber = value;
    }

}
