//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.31 at 04:47:15 PM CEST 
//


package hu.warchef.nav.domain.delta;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CustomerVatStatusType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CustomerVatStatusType"&gt;
 *   &lt;restriction base="{http://schemas.nav.gov.hu/NTCA/1.0/common}AtomicStringType15"&gt;
 *     &lt;enumeration value="DOMESTIC"/&gt;
 *     &lt;enumeration value="OTHER"/&gt;
 *     &lt;enumeration value="PRIVATE_PERSON"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "CustomerVatStatusType", namespace = "http://schemas.nav.gov.hu/OSA/3.0/data")
@XmlEnum
public enum CustomerVatStatusType {


    /**
     * Domestic VAT subject
     * 
     */
    DOMESTIC,

    /**
     * Other (domestic non-VAT subject, non-natural person, foreign VAT subject and foreign non-VAT subject, non-natural person)
     * 
     */
    OTHER,

    /**
     * Non-VAT subject (domestic or foreign) natural person
     * 
     */
    PRIVATE_PERSON;

    public String value() {
        return name();
    }

    public static CustomerVatStatusType fromValue(String v) {
        return valueOf(v);
    }

}
