//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.31 at 04:47:15 PM CEST 
//


package hu.warchef.nav.domain.delta;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IncorporationType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="IncorporationType"&gt;
 *   &lt;restriction base="{http://schemas.nav.gov.hu/NTCA/1.0/common}AtomicStringType15"&gt;
 *     &lt;enumeration value="ORGANIZATION"/&gt;
 *     &lt;enumeration value="SELF_EMPLOYED"/&gt;
 *     &lt;enumeration value="TAXABLE_PERSON"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "IncorporationType")
@XmlEnum
public enum IncorporationType {


    /**
     * Economical company
     * 
     */
    ORGANIZATION,

    /**
     * Self employed private entrepreneur
     * 
     */
    SELF_EMPLOYED,

    /**
     * Private person with tax number
     * 
     */
    TAXABLE_PERSON;

    public String value() {
        return name();
    }

    public static IncorporationType fromValue(String v) {
        return valueOf(v);
    }

}
