//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.31 at 04:47:15 PM CEST 
//


package hu.warchef.nav.domain.delta;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Batch invoice operations of the request
 * 
 * <p>Java class for InvoiceOperationListType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InvoiceOperationListType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="compressedContent" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="invoiceOperation" type="{http://schemas.nav.gov.hu/OSA/3.0/api}InvoiceOperationType" maxOccurs="100"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InvoiceOperationListType", propOrder = {
    "compressedContent",
    "invoiceOperation"
})
public class InvoiceOperationListType {

    protected boolean compressedContent;
    @XmlElement(required = true)
    protected List<InvoiceOperationType> invoiceOperation;

    /**
     * Gets the value of the compressedContent property.
     * 
     */
    public boolean isCompressedContent() {
        return compressedContent;
    }

    /**
     * Sets the value of the compressedContent property.
     * 
     */
    public void setCompressedContent(boolean value) {
        this.compressedContent = value;
    }

    /**
     * Gets the value of the invoiceOperation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the invoiceOperation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInvoiceOperation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InvoiceOperationType }
     * 
     * 
     */
    public List<InvoiceOperationType> getInvoiceOperation() {
        if (invoiceOperation == null) {
            invoiceOperation = new ArrayList<InvoiceOperationType>();
        }
        return this.invoiceOperation;
    }

}
