//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.31 at 04:47:15 PM CEST 
//


package hu.warchef.nav.domain.delta;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Invoice chain digest query result
 * 
 * <p>Java class for InvoiceChainDigestResultType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InvoiceChainDigestResultType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="currentPage" type="{http://schemas.nav.gov.hu/NTCA/1.0/common}ResponsePageType"/&gt;
 *         &lt;element name="availablePage" type="{http://schemas.nav.gov.hu/NTCA/1.0/common}ResponsePageType"/&gt;
 *         &lt;element name="invoiceChainElement" type="{http://schemas.nav.gov.hu/OSA/3.0/api}InvoiceChainElementType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InvoiceChainDigestResultType", propOrder = {
    "currentPage",
    "availablePage",
    "invoiceChainElement"
})
public class InvoiceChainDigestResultType {

    protected int currentPage;
    protected int availablePage;
    protected List<InvoiceChainElementType> invoiceChainElement;

    /**
     * Gets the value of the currentPage property.
     * 
     */
    public int getCurrentPage() {
        return currentPage;
    }

    /**
     * Sets the value of the currentPage property.
     * 
     */
    public void setCurrentPage(int value) {
        this.currentPage = value;
    }

    /**
     * Gets the value of the availablePage property.
     * 
     */
    public int getAvailablePage() {
        return availablePage;
    }

    /**
     * Sets the value of the availablePage property.
     * 
     */
    public void setAvailablePage(int value) {
        this.availablePage = value;
    }

    /**
     * Gets the value of the invoiceChainElement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the invoiceChainElement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInvoiceChainElement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InvoiceChainElementType }
     * 
     * 
     */
    public List<InvoiceChainElementType> getInvoiceChainElement() {
        if (invoiceChainElement == null) {
            invoiceChainElement = new ArrayList<InvoiceChainElementType>();
        }
        return this.invoiceChainElement;
    }

}
