//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.31 at 04:47:15 PM CEST 
//


package hu.warchef.nav.domain.delta;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Invoice exchange data
 * 
 * <p>Java class for InvoiceDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InvoiceDataType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="invoiceNumber" type="{http://schemas.nav.gov.hu/NTCA/1.0/common}SimpleText50NotBlankType"/&gt;
 *         &lt;element name="invoiceIssueDate" type="{http://schemas.nav.gov.hu/OSA/3.0/base}InvoiceDateType"/&gt;
 *         &lt;element name="completenessIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="invoiceMain" type="{http://schemas.nav.gov.hu/OSA/3.0/data}InvoiceMainType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InvoiceDataType", namespace = "http://schemas.nav.gov.hu/OSA/3.0/data", propOrder = {
    "invoiceNumber",
    "invoiceIssueDate",
    "completenessIndicator",
    "invoiceMain"
})
@XmlSeeAlso({
    InvoiceData.class
})
public class InvoiceDataType {

    @XmlElement(required = true)
    protected String invoiceNumber;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar invoiceIssueDate;
    protected boolean completenessIndicator;
    @XmlElement(required = true)
    protected InvoiceMainType invoiceMain;

    /**
     * Gets the value of the invoiceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInvoiceNumber() {
        return invoiceNumber;
    }

    /**
     * Sets the value of the invoiceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInvoiceNumber(String value) {
        this.invoiceNumber = value;
    }

    /**
     * Gets the value of the invoiceIssueDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getInvoiceIssueDate() {
        return invoiceIssueDate;
    }

    /**
     * Sets the value of the invoiceIssueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setInvoiceIssueDate(XMLGregorianCalendar value) {
        this.invoiceIssueDate = value;
    }

    /**
     * Gets the value of the completenessIndicator property.
     * 
     */
    public boolean isCompletenessIndicator() {
        return completenessIndicator;
    }

    /**
     * Sets the value of the completenessIndicator property.
     * 
     */
    public void setCompletenessIndicator(boolean value) {
        this.completenessIndicator = value;
    }

    /**
     * Gets the value of the invoiceMain property.
     * 
     * @return
     *     possible object is
     *     {@link InvoiceMainType }
     *     
     */
    public InvoiceMainType getInvoiceMain() {
        return invoiceMain;
    }

    /**
     * Sets the value of the invoiceMain property.
     * 
     * @param value
     *     allowed object is
     *     {@link InvoiceMainType }
     *     
     */
    public void setInvoiceMain(InvoiceMainType value) {
        this.invoiceMain = value;
    }

}
