//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.31 at 04:47:15 PM CEST 
//


package hu.warchef.nav.domain.delta;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Invoice operation of the request
 * 
 * <p>Java class for InvoiceOperationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InvoiceOperationType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="index" type="{http://schemas.nav.gov.hu/OSA/3.0/base}InvoiceIndexType"/&gt;
 *         &lt;element name="invoiceOperation" type="{http://schemas.nav.gov.hu/OSA/3.0/api}ManageInvoiceOperationType"/&gt;
 *         &lt;element name="invoiceData" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/&gt;
 *         &lt;element name="electronicInvoiceHash" type="{http://schemas.nav.gov.hu/NTCA/1.0/common}CryptoType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InvoiceOperationType", propOrder = {
    "index",
    "invoiceOperation",
    "invoiceData",
    "electronicInvoiceHash"
})
public class InvoiceOperationType {

    protected int index;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected ManageInvoiceOperationType invoiceOperation;
    @XmlElement(required = true)
    protected byte[] invoiceData;
    protected CryptoType electronicInvoiceHash;

    /**
     * Gets the value of the index property.
     * 
     */
    public int getIndex() {
        return index;
    }

    /**
     * Sets the value of the index property.
     * 
     */
    public void setIndex(int value) {
        this.index = value;
    }

    /**
     * Gets the value of the invoiceOperation property.
     * 
     * @return
     *     possible object is
     *     {@link ManageInvoiceOperationType }
     *     
     */
    public ManageInvoiceOperationType getInvoiceOperation() {
        return invoiceOperation;
    }

    /**
     * Sets the value of the invoiceOperation property.
     * 
     * @param value
     *     allowed object is
     *     {@link ManageInvoiceOperationType }
     *     
     */
    public void setInvoiceOperation(ManageInvoiceOperationType value) {
        this.invoiceOperation = value;
    }

    /**
     * Gets the value of the invoiceData property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getInvoiceData() {
        return invoiceData;
    }

    /**
     * Sets the value of the invoiceData property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setInvoiceData(byte[] value) {
        this.invoiceData = value;
    }

    /**
     * Gets the value of the electronicInvoiceHash property.
     * 
     * @return
     *     possible object is
     *     {@link CryptoType }
     *     
     */
    public CryptoType getElectronicInvoiceHash() {
        return electronicInvoiceHash;
    }

    /**
     * Sets the value of the electronicInvoiceHash property.
     * 
     * @param value
     *     allowed object is
     *     {@link CryptoType }
     *     
     */
    public void setElectronicInvoiceHash(CryptoType value) {
        this.electronicInvoiceHash = value;
    }

}
