//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.31 at 04:47:15 PM CEST 
//


package hu.warchef.nav.domain.delta;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Line VAT data
 * 
 * <p>Java class for LineVatDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LineVatDataType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="lineVatAmount" type="{http://schemas.nav.gov.hu/OSA/3.0/base}MonetaryType"/&gt;
 *         &lt;element name="lineVatAmountHUF" type="{http://schemas.nav.gov.hu/OSA/3.0/base}MonetaryType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LineVatDataType", namespace = "http://schemas.nav.gov.hu/OSA/3.0/data", propOrder = {
    "lineVatAmount",
    "lineVatAmountHUF"
})
public class LineVatDataType {

    @XmlElement(required = true)
    protected BigDecimal lineVatAmount;
    @XmlElement(required = true)
    protected BigDecimal lineVatAmountHUF;

    /**
     * Gets the value of the lineVatAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLineVatAmount() {
        return lineVatAmount;
    }

    /**
     * Sets the value of the lineVatAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLineVatAmount(BigDecimal value) {
        this.lineVatAmount = value;
    }

    /**
     * Gets the value of the lineVatAmountHUF property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLineVatAmountHUF() {
        return lineVatAmountHUF;
    }

    /**
     * Sets the value of the lineVatAmountHUF property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLineVatAmountHUF(BigDecimal value) {
        this.lineVatAmountHUF = value;
    }

}
