//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.31 at 04:47:15 PM CEST 
//


package hu.warchef.nav.domain.delta;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Item value data to be completed in case of simplified invoice
 * 
 * <p>Java class for LineAmountsSimplifiedType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LineAmountsSimplifiedType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="lineVatRate" type="{http://schemas.nav.gov.hu/OSA/3.0/data}VatRateType"/&gt;
 *         &lt;element name="lineGrossAmountSimplified" type="{http://schemas.nav.gov.hu/OSA/3.0/base}MonetaryType"/&gt;
 *         &lt;element name="lineGrossAmountSimplifiedHUF" type="{http://schemas.nav.gov.hu/OSA/3.0/base}MonetaryType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LineAmountsSimplifiedType", namespace = "http://schemas.nav.gov.hu/OSA/3.0/data", propOrder = {
    "lineVatRate",
    "lineGrossAmountSimplified",
    "lineGrossAmountSimplifiedHUF"
})
public class LineAmountsSimplifiedType {

    @XmlElement(required = true)
    protected VatRateType lineVatRate;
    @XmlElement(required = true)
    protected BigDecimal lineGrossAmountSimplified;
    @XmlElement(required = true)
    protected BigDecimal lineGrossAmountSimplifiedHUF;

    /**
     * Gets the value of the lineVatRate property.
     * 
     * @return
     *     possible object is
     *     {@link VatRateType }
     *     
     */
    public VatRateType getLineVatRate() {
        return lineVatRate;
    }

    /**
     * Sets the value of the lineVatRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link VatRateType }
     *     
     */
    public void setLineVatRate(VatRateType value) {
        this.lineVatRate = value;
    }

    /**
     * Gets the value of the lineGrossAmountSimplified property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLineGrossAmountSimplified() {
        return lineGrossAmountSimplified;
    }

    /**
     * Sets the value of the lineGrossAmountSimplified property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLineGrossAmountSimplified(BigDecimal value) {
        this.lineGrossAmountSimplified = value;
    }

    /**
     * Gets the value of the lineGrossAmountSimplifiedHUF property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLineGrossAmountSimplifiedHUF() {
        return lineGrossAmountSimplifiedHUF;
    }

    /**
     * Sets the value of the lineGrossAmountSimplifiedHUF property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLineGrossAmountSimplifiedHUF(BigDecimal value) {
        this.lineGrossAmountSimplifiedHUF = value;
    }

}
