//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.31 at 04:47:15 PM CEST 
//


package hu.warchef.nav.domain.delta;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ManageInvoiceOperationType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ManageInvoiceOperationType"&gt;
 *   &lt;restriction base="{http://schemas.nav.gov.hu/NTCA/1.0/common}AtomicStringType8"&gt;
 *     &lt;enumeration value="CREATE"/&gt;
 *     &lt;enumeration value="MODIFY"/&gt;
 *     &lt;enumeration value="STORNO"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "ManageInvoiceOperationType")
@XmlEnum
public enum ManageInvoiceOperationType {


    /**
     * Original invoice exchange
     * 
     */
    CREATE,

    /**
     * Modification invoice exchange
     * 
     */
    MODIFY,

    /**
     * Exchange concerning invoice invalidation
     * 
     */
    STORNO;

    public String value() {
        return name();
    }

    public static ManageInvoiceOperationType fromValue(String v) {
        return valueOf(v);
    }

}
