//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.31 at 04:47:15 PM CEST 
//


package hu.warchef.nav.domain.delta;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MetricTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="MetricTypeType"&gt;
 *   &lt;restriction base="{http://schemas.nav.gov.hu/NTCA/1.0/common}AtomicStringType15"&gt;
 *     &lt;enumeration value="COUNTER"/&gt;
 *     &lt;enumeration value="GAUGE"/&gt;
 *     &lt;enumeration value="HISTOGRAM"/&gt;
 *     &lt;enumeration value="SUMMARY"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "MetricTypeType", namespace = "http://schemas.nav.gov.hu/OSA/3.0/metrics")
@XmlEnum
public enum MetricTypeType {


    /**
     * Incremental type metric
     * 
     */
    COUNTER,

    /**
     * Snapshot type metric
     * 
     */
    GAUGE,

    /**
     * Quantile type, dispersion sampler metric
     * 
     */
    HISTOGRAM,

    /**
     * Sum value type metric
     * 
     */
    SUMMARY;

    public String value() {
        return name();
    }

    public static MetricTypeType fromValue(String v) {
        return valueOf(v);
    }

}
