//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.31 at 04:47:15 PM CEST 
//


package hu.warchef.nav.domain.delta;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Metric definition type
 * 
 * <p>Java class for MetricDefinitionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MetricDefinitionType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="metricName" type="{http://schemas.nav.gov.hu/NTCA/1.0/common}SimpleText200NotBlankType"/&gt;
 *         &lt;element name="metricType" type="{http://schemas.nav.gov.hu/OSA/3.0/metrics}MetricTypeType"/&gt;
 *         &lt;element name="metricDescription" type="{http://schemas.nav.gov.hu/OSA/3.0/metrics}MetricDescriptionType" maxOccurs="3" minOccurs="3"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MetricDefinitionType", namespace = "http://schemas.nav.gov.hu/OSA/3.0/metrics", propOrder = {
    "metricName",
    "metricType",
    "metricDescription"
})
public class MetricDefinitionType {

    @XmlElement(required = true)
    protected String metricName;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected MetricTypeType metricType;
    @XmlElement(required = true)
    protected List<MetricDescriptionType> metricDescription;

    /**
     * Gets the value of the metricName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMetricName() {
        return metricName;
    }

    /**
     * Sets the value of the metricName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMetricName(String value) {
        this.metricName = value;
    }

    /**
     * Gets the value of the metricType property.
     * 
     * @return
     *     possible object is
     *     {@link MetricTypeType }
     *     
     */
    public MetricTypeType getMetricType() {
        return metricType;
    }

    /**
     * Sets the value of the metricType property.
     * 
     * @param value
     *     allowed object is
     *     {@link MetricTypeType }
     *     
     */
    public void setMetricType(MetricTypeType value) {
        this.metricType = value;
    }

    /**
     * Gets the value of the metricDescription property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the metricDescription property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMetricDescription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MetricDescriptionType }
     * 
     * 
     */
    public List<MetricDescriptionType> getMetricDescription() {
        if (metricDescription == null) {
            metricDescription = new ArrayList<MetricDescriptionType>();
        }
        return this.metricDescription;
    }

}
