//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.31 at 04:47:15 PM CEST 
//


package hu.warchef.nav.domain.delta;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * New invoice lines created by the modification document
 * 
 * <p>Java class for NewCreatedLinesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NewCreatedLinesType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="lineNumberIntervalStart" type="{http://schemas.nav.gov.hu/OSA/3.0/base}LineNumberType"/&gt;
 *         &lt;element name="lineNumberIntervalEnd" type="{http://schemas.nav.gov.hu/OSA/3.0/base}LineNumberType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NewCreatedLinesType", propOrder = {
    "lineNumberIntervalStart",
    "lineNumberIntervalEnd"
})
public class NewCreatedLinesType {

    @XmlElement(required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger lineNumberIntervalStart;
    @XmlElement(required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger lineNumberIntervalEnd;

    /**
     * Gets the value of the lineNumberIntervalStart property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLineNumberIntervalStart() {
        return lineNumberIntervalStart;
    }

    /**
     * Sets the value of the lineNumberIntervalStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLineNumberIntervalStart(BigInteger value) {
        this.lineNumberIntervalStart = value;
    }

    /**
     * Gets the value of the lineNumberIntervalEnd property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLineNumberIntervalEnd() {
        return lineNumberIntervalEnd;
    }

    /**
     * Sets the value of the lineNumberIntervalEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLineNumberIntervalEnd(BigInteger value) {
        this.lineNumberIntervalEnd = value;
    }

}
