//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.31 at 04:47:15 PM CEST 
//


package hu.warchef.nav.domain.delta;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Supply of new means of transport - section 89 § and 169 (o) of the VAT law
 * 
 * <p>Java class for NewTransportMeanType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NewTransportMeanType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="brand" type="{http://schemas.nav.gov.hu/NTCA/1.0/common}SimpleText50NotBlankType" minOccurs="0"/&gt;
 *         &lt;element name="serialNum" type="{http://schemas.nav.gov.hu/NTCA/1.0/common}SimpleText255NotBlankType" minOccurs="0"/&gt;
 *         &lt;element name="engineNum" type="{http://schemas.nav.gov.hu/NTCA/1.0/common}SimpleText255NotBlankType" minOccurs="0"/&gt;
 *         &lt;element name="firstEntryIntoService" type="{http://schemas.nav.gov.hu/OSA/3.0/base}InvoiceDateType" minOccurs="0"/&gt;
 *         &lt;choice&gt;
 *           &lt;element name="vehicle" type="{http://schemas.nav.gov.hu/OSA/3.0/data}VehicleType"/&gt;
 *           &lt;element name="vessel" type="{http://schemas.nav.gov.hu/OSA/3.0/data}VesselType"/&gt;
 *           &lt;element name="aircraft" type="{http://schemas.nav.gov.hu/OSA/3.0/data}AircraftType"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NewTransportMeanType", namespace = "http://schemas.nav.gov.hu/OSA/3.0/data", propOrder = {
    "brand",
    "serialNum",
    "engineNum",
    "firstEntryIntoService",
    "vehicle",
    "vessel",
    "aircraft"
})
public class NewTransportMeanType {

    protected String brand;
    protected String serialNum;
    protected String engineNum;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar firstEntryIntoService;
    protected VehicleType vehicle;
    protected VesselType vessel;
    protected AircraftType aircraft;

    /**
     * Gets the value of the brand property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrand() {
        return brand;
    }

    /**
     * Sets the value of the brand property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrand(String value) {
        this.brand = value;
    }

    /**
     * Gets the value of the serialNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSerialNum() {
        return serialNum;
    }

    /**
     * Sets the value of the serialNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSerialNum(String value) {
        this.serialNum = value;
    }

    /**
     * Gets the value of the engineNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEngineNum() {
        return engineNum;
    }

    /**
     * Sets the value of the engineNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEngineNum(String value) {
        this.engineNum = value;
    }

    /**
     * Gets the value of the firstEntryIntoService property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFirstEntryIntoService() {
        return firstEntryIntoService;
    }

    /**
     * Sets the value of the firstEntryIntoService property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFirstEntryIntoService(XMLGregorianCalendar value) {
        this.firstEntryIntoService = value;
    }

    /**
     * Gets the value of the vehicle property.
     * 
     * @return
     *     possible object is
     *     {@link VehicleType }
     *     
     */
    public VehicleType getVehicle() {
        return vehicle;
    }

    /**
     * Sets the value of the vehicle property.
     * 
     * @param value
     *     allowed object is
     *     {@link VehicleType }
     *     
     */
    public void setVehicle(VehicleType value) {
        this.vehicle = value;
    }

    /**
     * Gets the value of the vessel property.
     * 
     * @return
     *     possible object is
     *     {@link VesselType }
     *     
     */
    public VesselType getVessel() {
        return vessel;
    }

    /**
     * Sets the value of the vessel property.
     * 
     * @param value
     *     allowed object is
     *     {@link VesselType }
     *     
     */
    public void setVessel(VesselType value) {
        this.vessel = value;
    }

    /**
     * Gets the value of the aircraft property.
     * 
     * @return
     *     possible object is
     *     {@link AircraftType }
     *     
     */
    public AircraftType getAircraft() {
        return aircraft;
    }

    /**
     * Sets the value of the aircraft property.
     * 
     * @param value
     *     allowed object is
     *     {@link AircraftType }
     *     
     */
    public void setAircraft(AircraftType value) {
        this.aircraft = value;
    }

}
