//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.31 at 04:47:15 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://schemas.nav.gov.hu/OSA/3.0/api", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package hu.warchef.nav.domain.delta;
