//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.31 at 04:47:15 PM CEST 
//


package hu.warchef.nav.domain.delta;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PaymentMethodType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PaymentMethodType"&gt;
 *   &lt;restriction base="{http://schemas.nav.gov.hu/NTCA/1.0/common}AtomicStringType15"&gt;
 *     &lt;enumeration value="TRANSFER"/&gt;
 *     &lt;enumeration value="CASH"/&gt;
 *     &lt;enumeration value="CARD"/&gt;
 *     &lt;enumeration value="VOUCHER"/&gt;
 *     &lt;enumeration value="OTHER"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "PaymentMethodType", namespace = "http://schemas.nav.gov.hu/OSA/3.0/base")
@XmlEnum
public enum PaymentMethodType {


    /**
     * Bank transfer
     * 
     */
    TRANSFER,

    /**
     * Cash
     * 
     */
    CASH,

    /**
     * Debit card, credit card, other cash-substitute payment instrument
     * 
     */
    CARD,

    /**
     * Voucher, bill of exchange, other non-cash payment instrument
     * 
     */
    VOUCHER,

    /**
     * Other
     * 
     */
    OTHER;

    public String value() {
        return name();
    }

    public static PaymentMethodType fromValue(String v) {
        return valueOf(v);
    }

}
