//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.31 at 04:47:15 PM CEST 
//


package hu.warchef.nav.domain.delta;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Response type of the POST /queryInvoiceDigest REST operation
 * 
 * <p>Java class for QueryInvoiceDigestResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QueryInvoiceDigestResponseType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://schemas.nav.gov.hu/OSA/3.0/api}BasicOnlineInvoiceResponseType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="invoiceDigestResult" type="{http://schemas.nav.gov.hu/OSA/3.0/api}InvoiceDigestResultType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QueryInvoiceDigestResponseType", propOrder = {
    "invoiceDigestResult"
})
@XmlSeeAlso({
    QueryInvoiceDigestResponse.class
})
public class QueryInvoiceDigestResponseType
    extends BasicOnlineInvoiceResponseType
{

    @XmlElement(required = true)
    protected InvoiceDigestResultType invoiceDigestResult;

    /**
     * Gets the value of the invoiceDigestResult property.
     * 
     * @return
     *     possible object is
     *     {@link InvoiceDigestResultType }
     *     
     */
    public InvoiceDigestResultType getInvoiceDigestResult() {
        return invoiceDigestResult;
    }

    /**
     * Sets the value of the invoiceDigestResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link InvoiceDigestResultType }
     *     
     */
    public void setInvoiceDigestResult(InvoiceDigestResultType value) {
        this.invoiceDigestResult = value;
    }

}
