//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.31 at 04:47:15 PM CEST 
//


package hu.warchef.nav.domain.delta;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Response type of the POST /queryInvoiceData REST operation
 * 
 * <p>Java class for QueryInvoiceDataResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QueryInvoiceDataResponseType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://schemas.nav.gov.hu/OSA/3.0/api}BasicOnlineInvoiceResponseType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="invoiceDataResult" type="{http://schemas.nav.gov.hu/OSA/3.0/api}InvoiceDataResultType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QueryInvoiceDataResponseType", propOrder = {
    "invoiceDataResult"
})
@XmlSeeAlso({
    QueryInvoiceDataResponse.class
})
public class QueryInvoiceDataResponseType
    extends BasicOnlineInvoiceResponseType
{

    protected InvoiceDataResultType invoiceDataResult;

    /**
     * Gets the value of the invoiceDataResult property.
     * 
     * @return
     *     possible object is
     *     {@link InvoiceDataResultType }
     *     
     */
    public InvoiceDataResultType getInvoiceDataResult() {
        return invoiceDataResult;
    }

    /**
     * Sets the value of the invoiceDataResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link InvoiceDataResultType }
     *     
     */
    public void setInvoiceDataResult(InvoiceDataResultType value) {
        this.invoiceDataResult = value;
    }

}
