//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.31 at 04:47:15 PM CEST 
//


package hu.warchef.nav.domain.delta;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Response type of the GET /queryServiceMetrics REST operation
 * 
 * <p>Java class for QueryServiceMetricsResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QueryServiceMetricsResponseType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="result" type="{http://schemas.nav.gov.hu/NTCA/1.0/common}BasicResultType"/&gt;
 *         &lt;element name="metricsLastUpdateTime" type="{http://schemas.nav.gov.hu/OSA/3.0/base}InvoiceTimestampType" minOccurs="0"/&gt;
 *         &lt;element name="metric" type="{http://schemas.nav.gov.hu/OSA/3.0/metrics}MetricType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QueryServiceMetricsResponseType", namespace = "http://schemas.nav.gov.hu/OSA/3.0/metrics", propOrder = {
    "result",
    "metricsLastUpdateTime",
    "metric"
})
@XmlSeeAlso({
    QueryServiceMetricsResponse.class
})
public class QueryServiceMetricsResponseType {

    @XmlElement(required = true)
    protected BasicResultType result;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar metricsLastUpdateTime;
    protected List<MetricType> metric;

    /**
     * Gets the value of the result property.
     * 
     * @return
     *     possible object is
     *     {@link BasicResultType }
     *     
     */
    public BasicResultType getResult() {
        return result;
    }

    /**
     * Sets the value of the result property.
     * 
     * @param value
     *     allowed object is
     *     {@link BasicResultType }
     *     
     */
    public void setResult(BasicResultType value) {
        this.result = value;
    }

    /**
     * Gets the value of the metricsLastUpdateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getMetricsLastUpdateTime() {
        return metricsLastUpdateTime;
    }

    /**
     * Sets the value of the metricsLastUpdateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setMetricsLastUpdateTime(XMLGregorianCalendar value) {
        this.metricsLastUpdateTime = value;
    }

    /**
     * Gets the value of the metric property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the metric property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMetric().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MetricType }
     * 
     * 
     */
    public List<MetricType> getMetric() {
        if (metric == null) {
            metric = new ArrayList<MetricType>();
        }
        return this.metric;
    }

}
