//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.31 at 04:47:15 PM CEST 
//


package hu.warchef.nav.domain.delta;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Relational params of the invoice query
 * 
 * <p>Java class for RelationalQueryParamsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RelationalQueryParamsType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="invoiceDelivery" type="{http://schemas.nav.gov.hu/OSA/3.0/api}RelationQueryDateType" maxOccurs="2" minOccurs="0"/&gt;
 *         &lt;element name="paymentDate" type="{http://schemas.nav.gov.hu/OSA/3.0/api}RelationQueryDateType" maxOccurs="2" minOccurs="0"/&gt;
 *         &lt;element name="invoiceNetAmount" type="{http://schemas.nav.gov.hu/OSA/3.0/api}RelationQueryMonetaryType" maxOccurs="2" minOccurs="0"/&gt;
 *         &lt;element name="invoiceNetAmountHUF" type="{http://schemas.nav.gov.hu/OSA/3.0/api}RelationQueryMonetaryType" maxOccurs="2" minOccurs="0"/&gt;
 *         &lt;element name="invoiceVatAmount" type="{http://schemas.nav.gov.hu/OSA/3.0/api}RelationQueryMonetaryType" maxOccurs="2" minOccurs="0"/&gt;
 *         &lt;element name="invoiceVatAmountHUF" type="{http://schemas.nav.gov.hu/OSA/3.0/api}RelationQueryMonetaryType" maxOccurs="2" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RelationalQueryParamsType", propOrder = {
    "invoiceDelivery",
    "paymentDate",
    "invoiceNetAmount",
    "invoiceNetAmountHUF",
    "invoiceVatAmount",
    "invoiceVatAmountHUF"
})
public class RelationalQueryParamsType {

    protected List<RelationQueryDateType> invoiceDelivery;
    protected List<RelationQueryDateType> paymentDate;
    protected List<RelationQueryMonetaryType> invoiceNetAmount;
    protected List<RelationQueryMonetaryType> invoiceNetAmountHUF;
    protected List<RelationQueryMonetaryType> invoiceVatAmount;
    protected List<RelationQueryMonetaryType> invoiceVatAmountHUF;

    /**
     * Gets the value of the invoiceDelivery property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the invoiceDelivery property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInvoiceDelivery().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RelationQueryDateType }
     * 
     * 
     */
    public List<RelationQueryDateType> getInvoiceDelivery() {
        if (invoiceDelivery == null) {
            invoiceDelivery = new ArrayList<RelationQueryDateType>();
        }
        return this.invoiceDelivery;
    }

    /**
     * Gets the value of the paymentDate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the paymentDate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPaymentDate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RelationQueryDateType }
     * 
     * 
     */
    public List<RelationQueryDateType> getPaymentDate() {
        if (paymentDate == null) {
            paymentDate = new ArrayList<RelationQueryDateType>();
        }
        return this.paymentDate;
    }

    /**
     * Gets the value of the invoiceNetAmount property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the invoiceNetAmount property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInvoiceNetAmount().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RelationQueryMonetaryType }
     * 
     * 
     */
    public List<RelationQueryMonetaryType> getInvoiceNetAmount() {
        if (invoiceNetAmount == null) {
            invoiceNetAmount = new ArrayList<RelationQueryMonetaryType>();
        }
        return this.invoiceNetAmount;
    }

    /**
     * Gets the value of the invoiceNetAmountHUF property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the invoiceNetAmountHUF property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInvoiceNetAmountHUF().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RelationQueryMonetaryType }
     * 
     * 
     */
    public List<RelationQueryMonetaryType> getInvoiceNetAmountHUF() {
        if (invoiceNetAmountHUF == null) {
            invoiceNetAmountHUF = new ArrayList<RelationQueryMonetaryType>();
        }
        return this.invoiceNetAmountHUF;
    }

    /**
     * Gets the value of the invoiceVatAmount property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the invoiceVatAmount property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInvoiceVatAmount().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RelationQueryMonetaryType }
     * 
     * 
     */
    public List<RelationQueryMonetaryType> getInvoiceVatAmount() {
        if (invoiceVatAmount == null) {
            invoiceVatAmount = new ArrayList<RelationQueryMonetaryType>();
        }
        return this.invoiceVatAmount;
    }

    /**
     * Gets the value of the invoiceVatAmountHUF property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the invoiceVatAmountHUF property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInvoiceVatAmountHUF().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RelationQueryMonetaryType }
     * 
     * 
     */
    public List<RelationQueryMonetaryType> getInvoiceVatAmountHUF() {
        if (invoiceVatAmountHUF == null) {
            invoiceVatAmountHUF = new ArrayList<RelationQueryMonetaryType>();
        }
        return this.invoiceVatAmountHUF;
    }

}
