//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.31 at 04:47:15 PM CEST 
//


package hu.warchef.nav.domain.delta;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Summary according to VAT rates
 * 
 * <p>Java class for SummaryByVatRateType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SummaryByVatRateType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="vatRate" type="{http://schemas.nav.gov.hu/OSA/3.0/data}VatRateType"/&gt;
 *         &lt;element name="vatRateNetData" type="{http://schemas.nav.gov.hu/OSA/3.0/data}VatRateNetDataType"/&gt;
 *         &lt;element name="vatRateVatData" type="{http://schemas.nav.gov.hu/OSA/3.0/data}VatRateVatDataType"/&gt;
 *         &lt;element name="vatRateGrossData" type="{http://schemas.nav.gov.hu/OSA/3.0/data}VatRateGrossDataType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SummaryByVatRateType", namespace = "http://schemas.nav.gov.hu/OSA/3.0/data", propOrder = {
    "vatRate",
    "vatRateNetData",
    "vatRateVatData",
    "vatRateGrossData"
})
public class SummaryByVatRateType {

    @XmlElement(required = true)
    protected VatRateType vatRate;
    @XmlElement(required = true)
    protected VatRateNetDataType vatRateNetData;
    @XmlElement(required = true)
    protected VatRateVatDataType vatRateVatData;
    protected VatRateGrossDataType vatRateGrossData;

    /**
     * Gets the value of the vatRate property.
     * 
     * @return
     *     possible object is
     *     {@link VatRateType }
     *     
     */
    public VatRateType getVatRate() {
        return vatRate;
    }

    /**
     * Sets the value of the vatRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link VatRateType }
     *     
     */
    public void setVatRate(VatRateType value) {
        this.vatRate = value;
    }

    /**
     * Gets the value of the vatRateNetData property.
     * 
     * @return
     *     possible object is
     *     {@link VatRateNetDataType }
     *     
     */
    public VatRateNetDataType getVatRateNetData() {
        return vatRateNetData;
    }

    /**
     * Sets the value of the vatRateNetData property.
     * 
     * @param value
     *     allowed object is
     *     {@link VatRateNetDataType }
     *     
     */
    public void setVatRateNetData(VatRateNetDataType value) {
        this.vatRateNetData = value;
    }

    /**
     * Gets the value of the vatRateVatData property.
     * 
     * @return
     *     possible object is
     *     {@link VatRateVatDataType }
     *     
     */
    public VatRateVatDataType getVatRateVatData() {
        return vatRateVatData;
    }

    /**
     * Sets the value of the vatRateVatData property.
     * 
     * @param value
     *     allowed object is
     *     {@link VatRateVatDataType }
     *     
     */
    public void setVatRateVatData(VatRateVatDataType value) {
        this.vatRateVatData = value;
    }

    /**
     * Gets the value of the vatRateGrossData property.
     * 
     * @return
     *     possible object is
     *     {@link VatRateGrossDataType }
     *     
     */
    public VatRateGrossDataType getVatRateGrossData() {
        return vatRateGrossData;
    }

    /**
     * Sets the value of the vatRateGrossData property.
     * 
     * @param value
     *     allowed object is
     *     {@link VatRateGrossDataType }
     *     
     */
    public void setVatRateGrossData(VatRateGrossDataType value) {
        this.vatRateGrossData = value;
    }

}
