//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.31 at 04:47:15 PM CEST 
//


package hu.warchef.nav.domain.delta;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Invoice supplier (seller) data
 * 
 * <p>Java class for SupplierInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SupplierInfoType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="supplierTaxNumber" type="{http://schemas.nav.gov.hu/OSA/3.0/base}TaxNumberType"/&gt;
 *         &lt;element name="groupMemberTaxNumber" type="{http://schemas.nav.gov.hu/OSA/3.0/base}TaxNumberType" minOccurs="0"/&gt;
 *         &lt;element name="communityVatNumber" type="{http://schemas.nav.gov.hu/NTCA/1.0/common}CommunityVatNumberType" minOccurs="0"/&gt;
 *         &lt;element name="supplierName" type="{http://schemas.nav.gov.hu/NTCA/1.0/common}SimpleText512NotBlankType"/&gt;
 *         &lt;element name="supplierAddress" type="{http://schemas.nav.gov.hu/OSA/3.0/base}AddressType"/&gt;
 *         &lt;element name="supplierBankAccountNumber" type="{http://schemas.nav.gov.hu/NTCA/1.0/common}BankAccountNumberType" minOccurs="0"/&gt;
 *         &lt;element name="individualExemption" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="exciseLicenceNum" type="{http://schemas.nav.gov.hu/NTCA/1.0/common}SimpleText50NotBlankType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SupplierInfoType", namespace = "http://schemas.nav.gov.hu/OSA/3.0/data", propOrder = {
    "supplierTaxNumber",
    "groupMemberTaxNumber",
    "communityVatNumber",
    "supplierName",
    "supplierAddress",
    "supplierBankAccountNumber",
    "individualExemption",
    "exciseLicenceNum"
})
public class SupplierInfoType {

    @XmlElement(required = true)
    protected TaxNumberType supplierTaxNumber;
    protected TaxNumberType groupMemberTaxNumber;
    protected String communityVatNumber;
    @XmlElement(required = true)
    protected String supplierName;
    @XmlElement(required = true)
    protected AddressType supplierAddress;
    protected String supplierBankAccountNumber;
    protected Boolean individualExemption;
    protected String exciseLicenceNum;

    /**
     * Gets the value of the supplierTaxNumber property.
     * 
     * @return
     *     possible object is
     *     {@link TaxNumberType }
     *     
     */
    public TaxNumberType getSupplierTaxNumber() {
        return supplierTaxNumber;
    }

    /**
     * Sets the value of the supplierTaxNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaxNumberType }
     *     
     */
    public void setSupplierTaxNumber(TaxNumberType value) {
        this.supplierTaxNumber = value;
    }

    /**
     * Gets the value of the groupMemberTaxNumber property.
     * 
     * @return
     *     possible object is
     *     {@link TaxNumberType }
     *     
     */
    public TaxNumberType getGroupMemberTaxNumber() {
        return groupMemberTaxNumber;
    }

    /**
     * Sets the value of the groupMemberTaxNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaxNumberType }
     *     
     */
    public void setGroupMemberTaxNumber(TaxNumberType value) {
        this.groupMemberTaxNumber = value;
    }

    /**
     * Gets the value of the communityVatNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommunityVatNumber() {
        return communityVatNumber;
    }

    /**
     * Sets the value of the communityVatNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommunityVatNumber(String value) {
        this.communityVatNumber = value;
    }

    /**
     * Gets the value of the supplierName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupplierName() {
        return supplierName;
    }

    /**
     * Sets the value of the supplierName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupplierName(String value) {
        this.supplierName = value;
    }

    /**
     * Gets the value of the supplierAddress property.
     * 
     * @return
     *     possible object is
     *     {@link AddressType }
     *     
     */
    public AddressType getSupplierAddress() {
        return supplierAddress;
    }

    /**
     * Sets the value of the supplierAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressType }
     *     
     */
    public void setSupplierAddress(AddressType value) {
        this.supplierAddress = value;
    }

    /**
     * Gets the value of the supplierBankAccountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupplierBankAccountNumber() {
        return supplierBankAccountNumber;
    }

    /**
     * Sets the value of the supplierBankAccountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupplierBankAccountNumber(String value) {
        this.supplierBankAccountNumber = value;
    }

    /**
     * Gets the value of the individualExemption property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIndividualExemption() {
        return individualExemption;
    }

    /**
     * Sets the value of the individualExemption property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIndividualExemption(Boolean value) {
        this.individualExemption = value;
    }

    /**
     * Gets the value of the exciseLicenceNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExciseLicenceNum() {
        return exciseLicenceNum;
    }

    /**
     * Sets the value of the exciseLicenceNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExciseLicenceNum(String value) {
        this.exciseLicenceNum = value;
    }

}
