//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.31 at 04:47:15 PM CEST 
//


package hu.warchef.nav.domain.delta;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Transactional params of the invoice query
 * 
 * <p>Java class for TransactionQueryParamsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TransactionQueryParamsType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="transactionId" type="{http://schemas.nav.gov.hu/NTCA/1.0/common}EntityIdType"/&gt;
 *         &lt;element name="index" type="{http://schemas.nav.gov.hu/OSA/3.0/base}InvoiceIndexType" minOccurs="0"/&gt;
 *         &lt;element name="invoiceOperation" type="{http://schemas.nav.gov.hu/OSA/3.0/api}ManageInvoiceOperationType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TransactionQueryParamsType", propOrder = {
    "transactionId",
    "index",
    "invoiceOperation"
})
public class TransactionQueryParamsType {

    @XmlElement(required = true)
    protected String transactionId;
    protected Integer index;
    @XmlSchemaType(name = "string")
    protected ManageInvoiceOperationType invoiceOperation;

    /**
     * Gets the value of the transactionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * Sets the value of the transactionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionId(String value) {
        this.transactionId = value;
    }

    /**
     * Gets the value of the index property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getIndex() {
        return index;
    }

    /**
     * Sets the value of the index property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setIndex(Integer value) {
        this.index = value;
    }

    /**
     * Gets the value of the invoiceOperation property.
     * 
     * @return
     *     possible object is
     *     {@link ManageInvoiceOperationType }
     *     
     */
    public ManageInvoiceOperationType getInvoiceOperation() {
        return invoiceOperation;
    }

    /**
     * Sets the value of the invoiceOperation property.
     * 
     * @param value
     *     allowed object is
     *     {@link ManageInvoiceOperationType }
     *     
     */
    public void setInvoiceOperation(ManageInvoiceOperationType value) {
        this.invoiceOperation = value;
    }

}
