//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.31 at 04:47:15 PM CEST 
//


package hu.warchef.nav.domain.delta;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Authentication data of the request
 * 
 * <p>Java class for UserHeaderType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UserHeaderType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="login" type="{http://schemas.nav.gov.hu/NTCA/1.0/common}LoginType"/&gt;
 *         &lt;element name="passwordHash" type="{http://schemas.nav.gov.hu/NTCA/1.0/common}CryptoType"/&gt;
 *         &lt;element name="taxNumber" type="{http://schemas.nav.gov.hu/NTCA/1.0/common}TaxpayerIdType"/&gt;
 *         &lt;element name="requestSignature" type="{http://schemas.nav.gov.hu/NTCA/1.0/common}CryptoType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UserHeaderType", namespace = "http://schemas.nav.gov.hu/NTCA/1.0/common", propOrder = {
    "login",
    "passwordHash",
    "taxNumber",
    "requestSignature"
})
public class UserHeaderType {

    @XmlElement(required = true)
    protected String login;
    @XmlElement(required = true)
    protected CryptoType passwordHash;
    @XmlElement(required = true)
    protected String taxNumber;
    @XmlElement(required = true)
    protected CryptoType requestSignature;

    /**
     * Gets the value of the login property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogin() {
        return login;
    }

    /**
     * Sets the value of the login property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogin(String value) {
        this.login = value;
    }

    /**
     * Gets the value of the passwordHash property.
     * 
     * @return
     *     possible object is
     *     {@link CryptoType }
     *     
     */
    public CryptoType getPasswordHash() {
        return passwordHash;
    }

    /**
     * Sets the value of the passwordHash property.
     * 
     * @param value
     *     allowed object is
     *     {@link CryptoType }
     *     
     */
    public void setPasswordHash(CryptoType value) {
        this.passwordHash = value;
    }

    /**
     * Gets the value of the taxNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxNumber() {
        return taxNumber;
    }

    /**
     * Sets the value of the taxNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxNumber(String value) {
        this.taxNumber = value;
    }

    /**
     * Gets the value of the requestSignature property.
     * 
     * @return
     *     possible object is
     *     {@link CryptoType }
     *     
     */
    public CryptoType getRequestSignature() {
        return requestSignature;
    }

    /**
     * Sets the value of the requestSignature property.
     * 
     * @param value
     *     allowed object is
     *     {@link CryptoType }
     *     
     */
    public void setRequestSignature(CryptoType value) {
        this.requestSignature = value;
    }

}
