//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.31 at 04:47:15 PM CEST 
//


package hu.warchef.nav.domain.delta;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Gross data of given tax rate
 * 
 * <p>Java class for VatRateGrossDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VatRateGrossDataType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="vatRateGrossAmount" type="{http://schemas.nav.gov.hu/OSA/3.0/base}MonetaryType"/&gt;
 *         &lt;element name="vatRateGrossAmountHUF" type="{http://schemas.nav.gov.hu/OSA/3.0/base}MonetaryType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VatRateGrossDataType", namespace = "http://schemas.nav.gov.hu/OSA/3.0/data", propOrder = {
    "vatRateGrossAmount",
    "vatRateGrossAmountHUF"
})
public class VatRateGrossDataType {

    @XmlElement(required = true)
    protected BigDecimal vatRateGrossAmount;
    @XmlElement(required = true)
    protected BigDecimal vatRateGrossAmountHUF;

    /**
     * Gets the value of the vatRateGrossAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVatRateGrossAmount() {
        return vatRateGrossAmount;
    }

    /**
     * Sets the value of the vatRateGrossAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVatRateGrossAmount(BigDecimal value) {
        this.vatRateGrossAmount = value;
    }

    /**
     * Gets the value of the vatRateGrossAmountHUF property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVatRateGrossAmountHUF() {
        return vatRateGrossAmountHUF;
    }

    /**
     * Sets the value of the vatRateGrossAmountHUF property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVatRateGrossAmountHUF(BigDecimal value) {
        this.vatRateGrossAmountHUF = value;
    }

}
