//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.31 at 04:47:23 PM CEST 
//


package hu.warchef.nav.domain.bravo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Format of address that includes either a simple or a detailed address
 * 
 * <p>Java class for AddressType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AddressType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="simpleAddress" type="{http://schemas.nav.gov.hu/OSA/1.0/data}SimpleAddressType"/&gt;
 *         &lt;element name="detailedAddress" type="{http://schemas.nav.gov.hu/OSA/1.0/data}DetailedAddressType"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AddressType", propOrder = {
    "simpleAddress",
    "detailedAddress"
})
public class AddressType {

    protected SimpleAddressType simpleAddress;
    protected DetailedAddressType detailedAddress;

    /**
     * Gets the value of the simpleAddress property.
     * 
     * @return
     *     possible object is
     *     {@link SimpleAddressType }
     *     
     */
    public SimpleAddressType getSimpleAddress() {
        return simpleAddress;
    }

    /**
     * Sets the value of the simpleAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleAddressType }
     *     
     */
    public void setSimpleAddress(SimpleAddressType value) {
        this.simpleAddress = value;
    }

    /**
     * Gets the value of the detailedAddress property.
     * 
     * @return
     *     possible object is
     *     {@link DetailedAddressType }
     *     
     */
    public DetailedAddressType getDetailedAddress() {
        return detailedAddress;
    }

    /**
     * Sets the value of the detailedAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link DetailedAddressType }
     *     
     */
    public void setDetailedAddress(DetailedAddressType value) {
        this.detailedAddress = value;
    }

}
