//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.31 at 04:47:23 PM CEST 
//


package hu.warchef.nav.domain.bravo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Fiscal representative data
 * 
 * <p>Java class for FiscalRepresentativeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FiscalRepresentativeType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="fiscalRepresentativeTaxNumber" type="{http://schemas.nav.gov.hu/OSA/1.0/data}TaxNumberType"/&gt;
 *         &lt;element name="fiscalRepresentativeName" type="{http://schemas.nav.gov.hu/OSA/1.0/data}SimpleText512NotBlankType"/&gt;
 *         &lt;element name="fiscalRepresentativeAddress" type="{http://schemas.nav.gov.hu/OSA/1.0/data}AddressType"/&gt;
 *         &lt;element name="fiscalRepresentativeBankAccountNumber" type="{http://schemas.nav.gov.hu/OSA/1.0/data}BankAccountNumberType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FiscalRepresentativeType", propOrder = {
    "fiscalRepresentativeTaxNumber",
    "fiscalRepresentativeName",
    "fiscalRepresentativeAddress",
    "fiscalRepresentativeBankAccountNumber"
})
public class FiscalRepresentativeType {

    @XmlElement(required = true)
    protected TaxNumberType fiscalRepresentativeTaxNumber;
    @XmlElement(required = true)
    protected String fiscalRepresentativeName;
    @XmlElement(required = true)
    protected AddressType fiscalRepresentativeAddress;
    protected String fiscalRepresentativeBankAccountNumber;

    /**
     * Gets the value of the fiscalRepresentativeTaxNumber property.
     * 
     * @return
     *     possible object is
     *     {@link TaxNumberType }
     *     
     */
    public TaxNumberType getFiscalRepresentativeTaxNumber() {
        return fiscalRepresentativeTaxNumber;
    }

    /**
     * Sets the value of the fiscalRepresentativeTaxNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaxNumberType }
     *     
     */
    public void setFiscalRepresentativeTaxNumber(TaxNumberType value) {
        this.fiscalRepresentativeTaxNumber = value;
    }

    /**
     * Gets the value of the fiscalRepresentativeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFiscalRepresentativeName() {
        return fiscalRepresentativeName;
    }

    /**
     * Sets the value of the fiscalRepresentativeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFiscalRepresentativeName(String value) {
        this.fiscalRepresentativeName = value;
    }

    /**
     * Gets the value of the fiscalRepresentativeAddress property.
     * 
     * @return
     *     possible object is
     *     {@link AddressType }
     *     
     */
    public AddressType getFiscalRepresentativeAddress() {
        return fiscalRepresentativeAddress;
    }

    /**
     * Sets the value of the fiscalRepresentativeAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressType }
     *     
     */
    public void setFiscalRepresentativeAddress(AddressType value) {
        this.fiscalRepresentativeAddress = value;
    }

    /**
     * Gets the value of the fiscalRepresentativeBankAccountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFiscalRepresentativeBankAccountNumber() {
        return fiscalRepresentativeBankAccountNumber;
    }

    /**
     * Sets the value of the fiscalRepresentativeBankAccountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFiscalRepresentativeBankAccountNumber(String value) {
        this.fiscalRepresentativeBankAccountNumber = value;
    }

}
