//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.31 at 04:47:23 PM CEST 
//


package hu.warchef.nav.domain.bravo;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Item value data to be completed in case of normal or aggregate invoice
 * 
 * <p>Java class for LineAmountsNormalType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LineAmountsNormalType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="lineNetAmount" type="{http://schemas.nav.gov.hu/OSA/1.0/data}MonetaryType"/&gt;
 *         &lt;element name="lineVatRate" type="{http://schemas.nav.gov.hu/OSA/1.0/data}VatRateType"/&gt;
 *         &lt;element name="lineVatAmount" type="{http://schemas.nav.gov.hu/OSA/1.0/data}MonetaryType" minOccurs="0"/&gt;
 *         &lt;element name="lineVatAmountHUF" type="{http://schemas.nav.gov.hu/OSA/1.0/data}MonetaryType" minOccurs="0"/&gt;
 *         &lt;element name="lineGrossAmountNormal" type="{http://schemas.nav.gov.hu/OSA/1.0/data}MonetaryType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LineAmountsNormalType", propOrder = {
    "lineNetAmount",
    "lineVatRate",
    "lineVatAmount",
    "lineVatAmountHUF",
    "lineGrossAmountNormal"
})
public class LineAmountsNormalType {

    @XmlElement(required = true)
    protected BigDecimal lineNetAmount;
    @XmlElement(required = true)
    protected VatRateType lineVatRate;
    protected BigDecimal lineVatAmount;
    protected BigDecimal lineVatAmountHUF;
    protected BigDecimal lineGrossAmountNormal;

    /**
     * Gets the value of the lineNetAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLineNetAmount() {
        return lineNetAmount;
    }

    /**
     * Sets the value of the lineNetAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLineNetAmount(BigDecimal value) {
        this.lineNetAmount = value;
    }

    /**
     * Gets the value of the lineVatRate property.
     * 
     * @return
     *     possible object is
     *     {@link VatRateType }
     *     
     */
    public VatRateType getLineVatRate() {
        return lineVatRate;
    }

    /**
     * Sets the value of the lineVatRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link VatRateType }
     *     
     */
    public void setLineVatRate(VatRateType value) {
        this.lineVatRate = value;
    }

    /**
     * Gets the value of the lineVatAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLineVatAmount() {
        return lineVatAmount;
    }

    /**
     * Sets the value of the lineVatAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLineVatAmount(BigDecimal value) {
        this.lineVatAmount = value;
    }

    /**
     * Gets the value of the lineVatAmountHUF property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLineVatAmountHUF() {
        return lineVatAmountHUF;
    }

    /**
     * Sets the value of the lineVatAmountHUF property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLineVatAmountHUF(BigDecimal value) {
        this.lineVatAmountHUF = value;
    }

    /**
     * Gets the value of the lineGrossAmountNormal property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLineGrossAmountNormal() {
        return lineGrossAmountNormal;
    }

    /**
     * Sets the value of the lineGrossAmountNormal property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLineGrossAmountNormal(BigDecimal value) {
        this.lineGrossAmountNormal = value;
    }

}
