//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.31 at 04:47:23 PM CEST 
//


package hu.warchef.nav.domain.bravo;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Marking the goal of modification of the line (in the case of data supply about changes/updates only)
 * 
 * <p>Java class for LineModificationReferenceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LineModificationReferenceType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="lineNumberReference" type="{http://schemas.nav.gov.hu/OSA/1.0/data}LineNumberType"/&gt;
 *         &lt;element name="lineOperation" type="{http://schemas.nav.gov.hu/OSA/1.0/data}LineOperationType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LineModificationReferenceType", propOrder = {
    "lineNumberReference",
    "lineOperation"
})
public class LineModificationReferenceType {

    @XmlElement(required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger lineNumberReference;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected LineOperationType lineOperation;

    /**
     * Gets the value of the lineNumberReference property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLineNumberReference() {
        return lineNumberReference;
    }

    /**
     * Sets the value of the lineNumberReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLineNumberReference(BigInteger value) {
        this.lineNumberReference = value;
    }

    /**
     * Gets the value of the lineOperation property.
     * 
     * @return
     *     possible object is
     *     {@link LineOperationType }
     *     
     */
    public LineOperationType getLineOperation() {
        return lineOperation;
    }

    /**
     * Sets the value of the lineOperation property.
     * 
     * @param value
     *     allowed object is
     *     {@link LineOperationType }
     *     
     */
    public void setLineOperation(LineOperationType value) {
        this.lineOperation = value;
    }

}
