//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.31 at 04:47:23 PM CEST 
//


package hu.warchef.nav.domain.bravo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Billing software data
 * 
 * <p>Java class for SoftwareType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SoftwareType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="softwareId" type="{http://schemas.nav.gov.hu/OSA/1.0/api}SoftwareIdType"/&gt;
 *         &lt;element name="softwareName" type="{http://schemas.nav.gov.hu/OSA/1.0/data}SimpleText50NotBlankType" minOccurs="0"/&gt;
 *         &lt;element name="softwareOperation" type="{http://schemas.nav.gov.hu/OSA/1.0/api}SoftwareOperationType" minOccurs="0"/&gt;
 *         &lt;element name="softwareMainVersion" type="{http://schemas.nav.gov.hu/OSA/1.0/data}SimpleText15NotBlankType" minOccurs="0"/&gt;
 *         &lt;element name="softwareDevName" type="{http://schemas.nav.gov.hu/OSA/1.0/data}SimpleText512NotBlankType" minOccurs="0"/&gt;
 *         &lt;element name="softwareDevContact" type="{http://schemas.nav.gov.hu/OSA/1.0/data}SimpleText200NotBlankType" minOccurs="0"/&gt;
 *         &lt;element name="softwareDevCountryCode" type="{http://schemas.nav.gov.hu/OSA/1.0/data}CountryCodeType" minOccurs="0"/&gt;
 *         &lt;element name="softwareDevTaxNumber" type="{http://schemas.nav.gov.hu/OSA/1.0/data}SimpleText50NotBlankType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SoftwareType", namespace = "http://schemas.nav.gov.hu/OSA/1.0/api", propOrder = {
    "softwareId",
    "softwareName",
    "softwareOperation",
    "softwareMainVersion",
    "softwareDevName",
    "softwareDevContact",
    "softwareDevCountryCode",
    "softwareDevTaxNumber"
})
public class SoftwareType {

    @XmlElement(required = true)
    protected String softwareId;
    protected String softwareName;
    @XmlSchemaType(name = "string")
    protected SoftwareOperationType softwareOperation;
    protected String softwareMainVersion;
    protected String softwareDevName;
    protected String softwareDevContact;
    protected String softwareDevCountryCode;
    protected String softwareDevTaxNumber;

    /**
     * Gets the value of the softwareId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoftwareId() {
        return softwareId;
    }

    /**
     * Sets the value of the softwareId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoftwareId(String value) {
        this.softwareId = value;
    }

    /**
     * Gets the value of the softwareName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoftwareName() {
        return softwareName;
    }

    /**
     * Sets the value of the softwareName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoftwareName(String value) {
        this.softwareName = value;
    }

    /**
     * Gets the value of the softwareOperation property.
     * 
     * @return
     *     possible object is
     *     {@link SoftwareOperationType }
     *     
     */
    public SoftwareOperationType getSoftwareOperation() {
        return softwareOperation;
    }

    /**
     * Sets the value of the softwareOperation property.
     * 
     * @param value
     *     allowed object is
     *     {@link SoftwareOperationType }
     *     
     */
    public void setSoftwareOperation(SoftwareOperationType value) {
        this.softwareOperation = value;
    }

    /**
     * Gets the value of the softwareMainVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoftwareMainVersion() {
        return softwareMainVersion;
    }

    /**
     * Sets the value of the softwareMainVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoftwareMainVersion(String value) {
        this.softwareMainVersion = value;
    }

    /**
     * Gets the value of the softwareDevName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoftwareDevName() {
        return softwareDevName;
    }

    /**
     * Sets the value of the softwareDevName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoftwareDevName(String value) {
        this.softwareDevName = value;
    }

    /**
     * Gets the value of the softwareDevContact property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoftwareDevContact() {
        return softwareDevContact;
    }

    /**
     * Sets the value of the softwareDevContact property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoftwareDevContact(String value) {
        this.softwareDevContact = value;
    }

    /**
     * Gets the value of the softwareDevCountryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoftwareDevCountryCode() {
        return softwareDevCountryCode;
    }

    /**
     * Sets the value of the softwareDevCountryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoftwareDevCountryCode(String value) {
        this.softwareDevCountryCode = value;
    }

    /**
     * Gets the value of the softwareDevTaxNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoftwareDevTaxNumber() {
        return softwareDevTaxNumber;
    }

    /**
     * Sets the value of the softwareDevTaxNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoftwareDevTaxNumber(String value) {
        this.softwareDevTaxNumber = value;
    }

}
