//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.31 at 04:47:23 PM CEST 
//


package hu.warchef.nav.domain.bravo;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Summary according to VAT rates
 * 
 * <p>Java class for SummaryByVatRateType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SummaryByVatRateType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="vatRate" type="{http://schemas.nav.gov.hu/OSA/1.0/data}VatRateType"/&gt;
 *         &lt;element name="vatRateNetAmount" type="{http://schemas.nav.gov.hu/OSA/1.0/data}MonetaryType"/&gt;
 *         &lt;element name="vatRateVatAmount" type="{http://schemas.nav.gov.hu/OSA/1.0/data}MonetaryType"/&gt;
 *         &lt;element name="vatRateVatAmountHUF" type="{http://schemas.nav.gov.hu/OSA/1.0/data}MonetaryType" minOccurs="0"/&gt;
 *         &lt;element name="vatRateGrossAmount" type="{http://schemas.nav.gov.hu/OSA/1.0/data}MonetaryType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SummaryByVatRateType", propOrder = {
    "vatRate",
    "vatRateNetAmount",
    "vatRateVatAmount",
    "vatRateVatAmountHUF",
    "vatRateGrossAmount"
})
public class SummaryByVatRateType {

    @XmlElement(required = true)
    protected VatRateType vatRate;
    @XmlElement(required = true)
    protected BigDecimal vatRateNetAmount;
    @XmlElement(required = true)
    protected BigDecimal vatRateVatAmount;
    protected BigDecimal vatRateVatAmountHUF;
    protected BigDecimal vatRateGrossAmount;

    /**
     * Gets the value of the vatRate property.
     * 
     * @return
     *     possible object is
     *     {@link VatRateType }
     *     
     */
    public VatRateType getVatRate() {
        return vatRate;
    }

    /**
     * Sets the value of the vatRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link VatRateType }
     *     
     */
    public void setVatRate(VatRateType value) {
        this.vatRate = value;
    }

    /**
     * Gets the value of the vatRateNetAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVatRateNetAmount() {
        return vatRateNetAmount;
    }

    /**
     * Sets the value of the vatRateNetAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVatRateNetAmount(BigDecimal value) {
        this.vatRateNetAmount = value;
    }

    /**
     * Gets the value of the vatRateVatAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVatRateVatAmount() {
        return vatRateVatAmount;
    }

    /**
     * Sets the value of the vatRateVatAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVatRateVatAmount(BigDecimal value) {
        this.vatRateVatAmount = value;
    }

    /**
     * Gets the value of the vatRateVatAmountHUF property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVatRateVatAmountHUF() {
        return vatRateVatAmountHUF;
    }

    /**
     * Sets the value of the vatRateVatAmountHUF property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVatRateVatAmountHUF(BigDecimal value) {
        this.vatRateVatAmountHUF = value;
    }

    /**
     * Gets the value of the vatRateGrossAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVatRateGrossAmount() {
        return vatRateGrossAmount;
    }

    /**
     * Sets the value of the vatRateGrossAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVatRateGrossAmount(BigDecimal value) {
        this.vatRateGrossAmount = value;
    }

}
