//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.31 at 04:47:25 PM CEST 
//


package hu.warchef.nav.domain.alpha;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Field type including data of invoice items (product or service)
 * 
 * <p>Java class for LineType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LineType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="lineNumber" type="{http://schemas.nav.gov.hu/OSA/1.0/data}LineNumberType"/&gt;
 *         &lt;element name="lineModificationReference" type="{http://schemas.nav.gov.hu/OSA/1.0/data}LineModificationReferenceType" minOccurs="0"/&gt;
 *         &lt;element name="referencesToOtherLines" type="{http://schemas.nav.gov.hu/OSA/1.0/data}ReferencesToOtherLinesType" minOccurs="0"/&gt;
 *         &lt;element name="advanceIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="productCodes" type="{http://schemas.nav.gov.hu/OSA/1.0/data}ProductCodesType" minOccurs="0"/&gt;
 *         &lt;element name="lineDescription" type="{http://schemas.nav.gov.hu/OSA/1.0/data}SimpleText255NotBlankType" minOccurs="0"/&gt;
 *         &lt;element name="quantity" type="{http://schemas.nav.gov.hu/OSA/1.0/data}QuantityType" minOccurs="0"/&gt;
 *         &lt;element name="unitOfMeasure" type="{http://schemas.nav.gov.hu/OSA/1.0/data}SimpleText50NotBlankType" minOccurs="0"/&gt;
 *         &lt;element name="unitPrice" type="{http://schemas.nav.gov.hu/OSA/1.0/data}QuantityType" minOccurs="0"/&gt;
 *         &lt;element name="lineDiscountData" type="{http://schemas.nav.gov.hu/OSA/1.0/data}DiscountDataType" minOccurs="0"/&gt;
 *         &lt;choice&gt;
 *           &lt;element name="lineAmountsNormal" type="{http://schemas.nav.gov.hu/OSA/1.0/data}LineAmountsNormalType" minOccurs="0"/&gt;
 *           &lt;element name="lineAmountsSimplified" type="{http://schemas.nav.gov.hu/OSA/1.0/data}LineAmountsSimplifiedType" minOccurs="0"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element name="intermediatedService" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="aggregateInvoiceLineData" type="{http://schemas.nav.gov.hu/OSA/1.0/data}AggregateInvoiceLineDataType" minOccurs="0"/&gt;
 *         &lt;element name="newTransportMean" type="{http://schemas.nav.gov.hu/OSA/1.0/data}NewTransportMeanType" minOccurs="0"/&gt;
 *         &lt;element name="depositIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="marginSchemeIndicator" type="{http://schemas.nav.gov.hu/OSA/1.0/data}MarginSchemeType" minOccurs="0"/&gt;
 *         &lt;element name="ekaerIds" type="{http://schemas.nav.gov.hu/OSA/1.0/data}EkaerIdsType" minOccurs="0"/&gt;
 *         &lt;element name="obligatedForProductFee" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="GPCExcise" type="{http://schemas.nav.gov.hu/OSA/1.0/data}MonetaryType" minOccurs="0"/&gt;
 *         &lt;element name="dieselOilPurchase" type="{http://schemas.nav.gov.hu/OSA/1.0/data}DieselOilPurchaseType" minOccurs="0"/&gt;
 *         &lt;element name="netaDeclaration" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="productFeeClause" type="{http://schemas.nav.gov.hu/OSA/1.0/data}ProductFeeClauseType" minOccurs="0"/&gt;
 *         &lt;element name="lineProductFeeContent" type="{http://schemas.nav.gov.hu/OSA/1.0/data}ProductFeeDataType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="additionalLineData" type="{http://schemas.nav.gov.hu/OSA/1.0/data}AdditionalDataType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LineType", propOrder = {
    "lineNumber",
    "lineModificationReference",
    "referencesToOtherLines",
    "advanceIndicator",
    "productCodes",
    "lineDescription",
    "quantity",
    "unitOfMeasure",
    "unitPrice",
    "lineDiscountData",
    "lineAmountsNormal",
    "lineAmountsSimplified",
    "intermediatedService",
    "aggregateInvoiceLineData",
    "newTransportMean",
    "depositIndicator",
    "marginSchemeIndicator",
    "ekaerIds",
    "obligatedForProductFee",
    "gpcExcise",
    "dieselOilPurchase",
    "netaDeclaration",
    "productFeeClause",
    "lineProductFeeContent",
    "additionalLineData"
})
public class LineType {

    @XmlElement(required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger lineNumber;
    protected LineModificationReferenceType lineModificationReference;
    protected ReferencesToOtherLinesType referencesToOtherLines;
    @XmlElement(defaultValue = "false")
    protected Boolean advanceIndicator;
    protected ProductCodesType productCodes;
    protected String lineDescription;
    protected BigDecimal quantity;
    protected String unitOfMeasure;
    protected BigDecimal unitPrice;
    protected DiscountDataType lineDiscountData;
    protected LineAmountsNormalType lineAmountsNormal;
    protected LineAmountsSimplifiedType lineAmountsSimplified;
    @XmlElement(defaultValue = "false")
    protected Boolean intermediatedService;
    protected AggregateInvoiceLineDataType aggregateInvoiceLineData;
    protected NewTransportMeanType newTransportMean;
    @XmlElement(defaultValue = "false")
    protected Boolean depositIndicator;
    @XmlSchemaType(name = "string")
    protected MarginSchemeType marginSchemeIndicator;
    protected EkaerIdsType ekaerIds;
    @XmlElement(defaultValue = "false")
    protected Boolean obligatedForProductFee;
    @XmlElement(name = "GPCExcise")
    protected BigDecimal gpcExcise;
    protected DieselOilPurchaseType dieselOilPurchase;
    @XmlElement(defaultValue = "false")
    protected Boolean netaDeclaration;
    protected ProductFeeClauseType productFeeClause;
    protected List<ProductFeeDataType> lineProductFeeContent;
    protected List<AdditionalDataType> additionalLineData;

    /**
     * Gets the value of the lineNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLineNumber() {
        return lineNumber;
    }

    /**
     * Sets the value of the lineNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLineNumber(BigInteger value) {
        this.lineNumber = value;
    }

    /**
     * Gets the value of the lineModificationReference property.
     * 
     * @return
     *     possible object is
     *     {@link LineModificationReferenceType }
     *     
     */
    public LineModificationReferenceType getLineModificationReference() {
        return lineModificationReference;
    }

    /**
     * Sets the value of the lineModificationReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link LineModificationReferenceType }
     *     
     */
    public void setLineModificationReference(LineModificationReferenceType value) {
        this.lineModificationReference = value;
    }

    /**
     * Gets the value of the referencesToOtherLines property.
     * 
     * @return
     *     possible object is
     *     {@link ReferencesToOtherLinesType }
     *     
     */
    public ReferencesToOtherLinesType getReferencesToOtherLines() {
        return referencesToOtherLines;
    }

    /**
     * Sets the value of the referencesToOtherLines property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferencesToOtherLinesType }
     *     
     */
    public void setReferencesToOtherLines(ReferencesToOtherLinesType value) {
        this.referencesToOtherLines = value;
    }

    /**
     * Gets the value of the advanceIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAdvanceIndicator() {
        return advanceIndicator;
    }

    /**
     * Sets the value of the advanceIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAdvanceIndicator(Boolean value) {
        this.advanceIndicator = value;
    }

    /**
     * Gets the value of the productCodes property.
     * 
     * @return
     *     possible object is
     *     {@link ProductCodesType }
     *     
     */
    public ProductCodesType getProductCodes() {
        return productCodes;
    }

    /**
     * Sets the value of the productCodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductCodesType }
     *     
     */
    public void setProductCodes(ProductCodesType value) {
        this.productCodes = value;
    }

    /**
     * Gets the value of the lineDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLineDescription() {
        return lineDescription;
    }

    /**
     * Sets the value of the lineDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLineDescription(String value) {
        this.lineDescription = value;
    }

    /**
     * Gets the value of the quantity property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setQuantity(BigDecimal value) {
        this.quantity = value;
    }

    /**
     * Gets the value of the unitOfMeasure property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnitOfMeasure() {
        return unitOfMeasure;
    }

    /**
     * Sets the value of the unitOfMeasure property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnitOfMeasure(String value) {
        this.unitOfMeasure = value;
    }

    /**
     * Gets the value of the unitPrice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getUnitPrice() {
        return unitPrice;
    }

    /**
     * Sets the value of the unitPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setUnitPrice(BigDecimal value) {
        this.unitPrice = value;
    }

    /**
     * Gets the value of the lineDiscountData property.
     * 
     * @return
     *     possible object is
     *     {@link DiscountDataType }
     *     
     */
    public DiscountDataType getLineDiscountData() {
        return lineDiscountData;
    }

    /**
     * Sets the value of the lineDiscountData property.
     * 
     * @param value
     *     allowed object is
     *     {@link DiscountDataType }
     *     
     */
    public void setLineDiscountData(DiscountDataType value) {
        this.lineDiscountData = value;
    }

    /**
     * Gets the value of the lineAmountsNormal property.
     * 
     * @return
     *     possible object is
     *     {@link LineAmountsNormalType }
     *     
     */
    public LineAmountsNormalType getLineAmountsNormal() {
        return lineAmountsNormal;
    }

    /**
     * Sets the value of the lineAmountsNormal property.
     * 
     * @param value
     *     allowed object is
     *     {@link LineAmountsNormalType }
     *     
     */
    public void setLineAmountsNormal(LineAmountsNormalType value) {
        this.lineAmountsNormal = value;
    }

    /**
     * Gets the value of the lineAmountsSimplified property.
     * 
     * @return
     *     possible object is
     *     {@link LineAmountsSimplifiedType }
     *     
     */
    public LineAmountsSimplifiedType getLineAmountsSimplified() {
        return lineAmountsSimplified;
    }

    /**
     * Sets the value of the lineAmountsSimplified property.
     * 
     * @param value
     *     allowed object is
     *     {@link LineAmountsSimplifiedType }
     *     
     */
    public void setLineAmountsSimplified(LineAmountsSimplifiedType value) {
        this.lineAmountsSimplified = value;
    }

    /**
     * Gets the value of the intermediatedService property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIntermediatedService() {
        return intermediatedService;
    }

    /**
     * Sets the value of the intermediatedService property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIntermediatedService(Boolean value) {
        this.intermediatedService = value;
    }

    /**
     * Gets the value of the aggregateInvoiceLineData property.
     * 
     * @return
     *     possible object is
     *     {@link AggregateInvoiceLineDataType }
     *     
     */
    public AggregateInvoiceLineDataType getAggregateInvoiceLineData() {
        return aggregateInvoiceLineData;
    }

    /**
     * Sets the value of the aggregateInvoiceLineData property.
     * 
     * @param value
     *     allowed object is
     *     {@link AggregateInvoiceLineDataType }
     *     
     */
    public void setAggregateInvoiceLineData(AggregateInvoiceLineDataType value) {
        this.aggregateInvoiceLineData = value;
    }

    /**
     * Gets the value of the newTransportMean property.
     * 
     * @return
     *     possible object is
     *     {@link NewTransportMeanType }
     *     
     */
    public NewTransportMeanType getNewTransportMean() {
        return newTransportMean;
    }

    /**
     * Sets the value of the newTransportMean property.
     * 
     * @param value
     *     allowed object is
     *     {@link NewTransportMeanType }
     *     
     */
    public void setNewTransportMean(NewTransportMeanType value) {
        this.newTransportMean = value;
    }

    /**
     * Gets the value of the depositIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDepositIndicator() {
        return depositIndicator;
    }

    /**
     * Sets the value of the depositIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDepositIndicator(Boolean value) {
        this.depositIndicator = value;
    }

    /**
     * Gets the value of the marginSchemeIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link MarginSchemeType }
     *     
     */
    public MarginSchemeType getMarginSchemeIndicator() {
        return marginSchemeIndicator;
    }

    /**
     * Sets the value of the marginSchemeIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link MarginSchemeType }
     *     
     */
    public void setMarginSchemeIndicator(MarginSchemeType value) {
        this.marginSchemeIndicator = value;
    }

    /**
     * Gets the value of the ekaerIds property.
     * 
     * @return
     *     possible object is
     *     {@link EkaerIdsType }
     *     
     */
    public EkaerIdsType getEkaerIds() {
        return ekaerIds;
    }

    /**
     * Sets the value of the ekaerIds property.
     * 
     * @param value
     *     allowed object is
     *     {@link EkaerIdsType }
     *     
     */
    public void setEkaerIds(EkaerIdsType value) {
        this.ekaerIds = value;
    }

    /**
     * Gets the value of the obligatedForProductFee property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isObligatedForProductFee() {
        return obligatedForProductFee;
    }

    /**
     * Sets the value of the obligatedForProductFee property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setObligatedForProductFee(Boolean value) {
        this.obligatedForProductFee = value;
    }

    /**
     * Gets the value of the gpcExcise property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getGPCExcise() {
        return gpcExcise;
    }

    /**
     * Sets the value of the gpcExcise property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setGPCExcise(BigDecimal value) {
        this.gpcExcise = value;
    }

    /**
     * Gets the value of the dieselOilPurchase property.
     * 
     * @return
     *     possible object is
     *     {@link DieselOilPurchaseType }
     *     
     */
    public DieselOilPurchaseType getDieselOilPurchase() {
        return dieselOilPurchase;
    }

    /**
     * Sets the value of the dieselOilPurchase property.
     * 
     * @param value
     *     allowed object is
     *     {@link DieselOilPurchaseType }
     *     
     */
    public void setDieselOilPurchase(DieselOilPurchaseType value) {
        this.dieselOilPurchase = value;
    }

    /**
     * Gets the value of the netaDeclaration property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isNetaDeclaration() {
        return netaDeclaration;
    }

    /**
     * Sets the value of the netaDeclaration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setNetaDeclaration(Boolean value) {
        this.netaDeclaration = value;
    }

    /**
     * Gets the value of the productFeeClause property.
     * 
     * @return
     *     possible object is
     *     {@link ProductFeeClauseType }
     *     
     */
    public ProductFeeClauseType getProductFeeClause() {
        return productFeeClause;
    }

    /**
     * Sets the value of the productFeeClause property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductFeeClauseType }
     *     
     */
    public void setProductFeeClause(ProductFeeClauseType value) {
        this.productFeeClause = value;
    }

    /**
     * Gets the value of the lineProductFeeContent property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lineProductFeeContent property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLineProductFeeContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProductFeeDataType }
     * 
     * 
     */
    public List<ProductFeeDataType> getLineProductFeeContent() {
        if (lineProductFeeContent == null) {
            lineProductFeeContent = new ArrayList<ProductFeeDataType>();
        }
        return this.lineProductFeeContent;
    }

    /**
     * Gets the value of the additionalLineData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the additionalLineData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdditionalLineData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AdditionalDataType }
     * 
     * 
     */
    public List<AdditionalDataType> getAdditionalLineData() {
        if (additionalLineData == null) {
            additionalLineData = new ArrayList<AdditionalDataType>();
        }
        return this.additionalLineData;
    }

}
