//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.31 at 04:47:25 PM CEST 
//


package hu.warchef.nav.domain.alpha;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Item value data to be completed in case of simplified invoice
 * 
 * <p>Java class for LineAmountsSimplifiedType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LineAmountsSimplifiedType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="lineVatContent" type="{http://schemas.nav.gov.hu/OSA/1.0/data}RateType" minOccurs="0"/&gt;
 *         &lt;element name="lineGrossAmountSimplified" type="{http://schemas.nav.gov.hu/OSA/1.0/data}MonetaryType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LineAmountsSimplifiedType", propOrder = {
    "lineVatContent",
    "lineGrossAmountSimplified"
})
public class LineAmountsSimplifiedType {

    protected BigDecimal lineVatContent;
    @XmlElement(required = true)
    protected BigDecimal lineGrossAmountSimplified;

    /**
     * Gets the value of the lineVatContent property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLineVatContent() {
        return lineVatContent;
    }

    /**
     * Sets the value of the lineVatContent property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLineVatContent(BigDecimal value) {
        this.lineVatContent = value;
    }

    /**
     * Gets the value of the lineGrossAmountSimplified property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLineGrossAmountSimplified() {
        return lineGrossAmountSimplified;
    }

    /**
     * Sets the value of the lineGrossAmountSimplified property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLineGrossAmountSimplified(BigDecimal value) {
        this.lineGrossAmountSimplified = value;
    }

}
