//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.31 at 04:47:25 PM CEST 
//


package hu.warchef.nav.domain.alpha;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://schemas.nav.gov.hu/OSA/1.0/api}BasicRequestType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="exchangeToken" type="{http://schemas.nav.gov.hu/OSA/1.0/data}SimpleText50NotBlankType"/&gt;
 *         &lt;element name="invoiceOperations" type="{http://schemas.nav.gov.hu/OSA/1.0/api}InvoiceOperationListType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "exchangeToken",
    "invoiceOperations"
})
@XmlRootElement(name = "ManageInvoiceRequest", namespace = "http://schemas.nav.gov.hu/OSA/1.0/api")
public class ManageInvoiceRequest
    extends BasicRequestType
{

    @XmlElement(namespace = "http://schemas.nav.gov.hu/OSA/1.0/api", required = true)
    protected String exchangeToken;
    @XmlElement(namespace = "http://schemas.nav.gov.hu/OSA/1.0/api", required = true)
    protected InvoiceOperationListType invoiceOperations;

    /**
     * Gets the value of the exchangeToken property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExchangeToken() {
        return exchangeToken;
    }

    /**
     * Sets the value of the exchangeToken property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExchangeToken(String value) {
        this.exchangeToken = value;
    }

    /**
     * Gets the value of the invoiceOperations property.
     * 
     * @return
     *     possible object is
     *     {@link InvoiceOperationListType }
     *     
     */
    public InvoiceOperationListType getInvoiceOperations() {
        return invoiceOperations;
    }

    /**
     * Sets the value of the invoiceOperations property.
     * 
     * @param value
     *     allowed object is
     *     {@link InvoiceOperationListType }
     *     
     */
    public void setInvoiceOperations(InvoiceOperationListType value) {
        this.invoiceOperations = value;
    }

}
