//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.31 at 04:47:25 PM CEST 
//


package hu.warchef.nav.domain.alpha;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Product charges data
 * 
 * <p>Java class for ProductFeeDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProductFeeDataType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="productFeeCode" type="{http://schemas.nav.gov.hu/OSA/1.0/data}ProductCodeType"/&gt;
 *         &lt;element name="productFeeQuantity" type="{http://schemas.nav.gov.hu/OSA/1.0/data}QuantityType"/&gt;
 *         &lt;element name="productFeeMeasuringUnit" type="{http://schemas.nav.gov.hu/OSA/1.0/data}ProductFeeMeasuringUnitType"/&gt;
 *         &lt;element name="productFeeRate" type="{http://schemas.nav.gov.hu/OSA/1.0/data}MonetaryType"/&gt;
 *         &lt;element name="productFeeAmount" type="{http://schemas.nav.gov.hu/OSA/1.0/data}MonetaryType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProductFeeDataType", propOrder = {
    "productFeeCode",
    "productFeeQuantity",
    "productFeeMeasuringUnit",
    "productFeeRate",
    "productFeeAmount"
})
public class ProductFeeDataType {

    @XmlElement(required = true)
    protected ProductCodeType productFeeCode;
    @XmlElement(required = true)
    protected BigDecimal productFeeQuantity;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected ProductFeeMeasuringUnitType productFeeMeasuringUnit;
    @XmlElement(required = true)
    protected BigDecimal productFeeRate;
    @XmlElement(required = true)
    protected BigDecimal productFeeAmount;

    /**
     * Gets the value of the productFeeCode property.
     * 
     * @return
     *     possible object is
     *     {@link ProductCodeType }
     *     
     */
    public ProductCodeType getProductFeeCode() {
        return productFeeCode;
    }

    /**
     * Sets the value of the productFeeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductCodeType }
     *     
     */
    public void setProductFeeCode(ProductCodeType value) {
        this.productFeeCode = value;
    }

    /**
     * Gets the value of the productFeeQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getProductFeeQuantity() {
        return productFeeQuantity;
    }

    /**
     * Sets the value of the productFeeQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setProductFeeQuantity(BigDecimal value) {
        this.productFeeQuantity = value;
    }

    /**
     * Gets the value of the productFeeMeasuringUnit property.
     * 
     * @return
     *     possible object is
     *     {@link ProductFeeMeasuringUnitType }
     *     
     */
    public ProductFeeMeasuringUnitType getProductFeeMeasuringUnit() {
        return productFeeMeasuringUnit;
    }

    /**
     * Sets the value of the productFeeMeasuringUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductFeeMeasuringUnitType }
     *     
     */
    public void setProductFeeMeasuringUnit(ProductFeeMeasuringUnitType value) {
        this.productFeeMeasuringUnit = value;
    }

    /**
     * Gets the value of the productFeeRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getProductFeeRate() {
        return productFeeRate;
    }

    /**
     * Sets the value of the productFeeRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setProductFeeRate(BigDecimal value) {
        this.productFeeRate = value;
    }

    /**
     * Gets the value of the productFeeAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getProductFeeAmount() {
        return productFeeAmount;
    }

    /**
     * Sets the value of the productFeeAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setProductFeeAmount(BigDecimal value) {
        this.productFeeAmount = value;
    }

}
