//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.31 at 04:47:25 PM CEST 
//


package hu.warchef.nav.domain.alpha;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://schemas.nav.gov.hu/OSA/1.0/api}BasicResponseType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="taxpayerValidity" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="taxpayerData" type="{http://schemas.nav.gov.hu/OSA/1.0/api}TaxpayerDataType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "taxpayerValidity",
    "taxpayerData"
})
@XmlRootElement(name = "QueryTaxpayerResponse", namespace = "http://schemas.nav.gov.hu/OSA/1.0/api")
public class QueryTaxpayerResponse
    extends BasicResponseType
{

    @XmlElement(namespace = "http://schemas.nav.gov.hu/OSA/1.0/api")
    protected Boolean taxpayerValidity;
    @XmlElement(namespace = "http://schemas.nav.gov.hu/OSA/1.0/api")
    protected TaxpayerDataType taxpayerData;

    /**
     * Gets the value of the taxpayerValidity property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isTaxpayerValidity() {
        return taxpayerValidity;
    }

    /**
     * Sets the value of the taxpayerValidity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTaxpayerValidity(Boolean value) {
        this.taxpayerValidity = value;
    }

    /**
     * Gets the value of the taxpayerData property.
     * 
     * @return
     *     possible object is
     *     {@link TaxpayerDataType }
     *     
     */
    public TaxpayerDataType getTaxpayerData() {
        return taxpayerData;
    }

    /**
     * Sets the value of the taxpayerData property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaxpayerDataType }
     *     
     */
    public void setTaxpayerData(TaxpayerDataType value) {
        this.taxpayerData = value;
    }

}
