//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.31 at 04:47:25 PM CEST 
//


package hu.warchef.nav.domain.alpha;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://schemas.nav.gov.hu/OSA/1.0/api}BasicRequestType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="page" type="{http://schemas.nav.gov.hu/OSA/1.0/api}PageType"/&gt;
 *         &lt;choice&gt;
 *           &lt;element name="invoiceQuery" type="{http://schemas.nav.gov.hu/OSA/1.0/api}InvoiceQueryType"/&gt;
 *           &lt;element name="queryParams" type="{http://schemas.nav.gov.hu/OSA/1.0/api}InvoiceQueryParamsType"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "page",
    "invoiceQuery",
    "queryParams"
})
@XmlRootElement(name = "QueryInvoiceDataRequest", namespace = "http://schemas.nav.gov.hu/OSA/1.0/api")
public class QueryInvoiceDataRequest
    extends BasicRequestType
{

    @XmlElement(namespace = "http://schemas.nav.gov.hu/OSA/1.0/api")
    protected int page;
    @XmlElement(namespace = "http://schemas.nav.gov.hu/OSA/1.0/api")
    protected InvoiceQueryType invoiceQuery;
    @XmlElement(namespace = "http://schemas.nav.gov.hu/OSA/1.0/api")
    protected InvoiceQueryParamsType queryParams;

    /**
     * Gets the value of the page property.
     * 
     */
    public int getPage() {
        return page;
    }

    /**
     * Sets the value of the page property.
     * 
     */
    public void setPage(int value) {
        this.page = value;
    }

    /**
     * Gets the value of the invoiceQuery property.
     * 
     * @return
     *     possible object is
     *     {@link InvoiceQueryType }
     *     
     */
    public InvoiceQueryType getInvoiceQuery() {
        return invoiceQuery;
    }

    /**
     * Sets the value of the invoiceQuery property.
     * 
     * @param value
     *     allowed object is
     *     {@link InvoiceQueryType }
     *     
     */
    public void setInvoiceQuery(InvoiceQueryType value) {
        this.invoiceQuery = value;
    }

    /**
     * Gets the value of the queryParams property.
     * 
     * @return
     *     possible object is
     *     {@link InvoiceQueryParamsType }
     *     
     */
    public InvoiceQueryParamsType getQueryParams() {
        return queryParams;
    }

    /**
     * Sets the value of the queryParams property.
     * 
     * @param value
     *     allowed object is
     *     {@link InvoiceQueryParamsType }
     *     
     */
    public void setQueryParams(InvoiceQueryParamsType value) {
        this.queryParams = value;
    }

}
